- tools/codemod/codemod.ts
- tools/codemod/src/v4.0.0/abstract.ts
- tools/codemod/src/v4.0.0/backstage-item.ts
- tools/codemod/src/v4.0.0/frontstage-to-config.ts
- tools/codemod/src/v4.0.0/full.ts
- tools/codemod/src/v4.0.0/layout-react.ts
- tools/codemod/src/v4.0.0/react.ts
- tools/codemod/src/v4.0.0/statics.ts
- tools/codemod/src/v4.0.0/status-bar-item.ts
- tools/codemod/src/v4.0.0/toolbar-item.ts
- tools/codemod/src/v4.0.0/ui-items-provider.ts
- tools/codemod/src/v4.0.0/widget-to-config.ts
- tools/codemod/src/v4.0.0/widget.ts
Also ignore files under **node_modules** by default.
> Add printOptions option to codemod

- changehistory/NextVersion.md
Add webfont depency removal to NextVersion.md
> Webfont next version

- common/api/imodel-components-react.api.md
- common/changes/@itwin/imodel-components-react/navigation-experiments_2023-03-20-22-19.json
- ui/imodel-components-react/src/imodel-components-react/navigationaids/CubeNavigationAid.tsx
- ui/imodel-components-react/src/test/navigationaids/CubeNavigationAid.test.tsx
Update CubeNavigationAid in line with current design goals.
> Navigation experiments

- docs/changehistory/NextVersion.md
Add missing information about SCSS variables removal and IModelConnectedViewport no longer being wrapped by unifiedSelection from presentation-components
> Add SCSS and unified selection notices.

- common/changes/@itwin/appui-react/core-telemetry-peer-dep_2023-04-06-10-26.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/variants/core-3x/pnpm-lock.yaml
- ui/appui-react/package.json
> Move @itwin/core-telemetry to peerDependencies

- common/changes/@itwin/appui-codemod/codemod-fix_2023-04-12-16-33.json
- tools/codemod/src/utils/CallExpression.ts
- tools/codemod/src/utils/Extensions.ts
- tools/codemod/src/utils/__tests__/CallExpression.test.ts
- tools/codemod/src/utils/__tests__/Extensions.test.ts
- tools/codemod/src/v4.0.0/__tests__/statics.test.ts
This PR fixes an issue where duplicate specifiers are added by one of transformers failing subsequent transformers.
> Fix duplicate specifiers

- common/changes/@itwin/components-react/Fix_property_record_value_overflow_2023-04-12-13-29.json
- ui/components-react/src/components-react/properties/renderers/PropertyView.scss
> Fix property record value overflow

- common/changes/@itwin/components-react/Fix_multiline_text_property_value_renderer_2023-05-08-12-34.json
- ui/components-react/src/components-react/properties/renderers/PropertyView.scss
- ui/components-react/src/components-react/properties/renderers/value/MultilineTextPropertyValueRenderer.tsx
- ui/components-react/src/test/properties/renderers/MultilineTextPropertyValueRenderer.test.tsx
Closes ITwin/presentation#144
N/A
> Fix multiline text property value renderer

- common/changes/@itwin/appui-react/fix-docs-link_2023-05-12-12-00.json
- ui/appui-react/src/appui-react/frontstage/StandardFrontstageProvider.tsx
Reference `UiItemsProvider` from `appui-react`.
N/A
> Reference UiItemsProvider from appui-react

- common/changes/@itwin/appui-layout-react/backport-4.1.0_2023-05-31-10-33.json
- common/changes/@itwin/appui-react/backport-4.1.0_2023-05-31-10-33.json
- common/changes/@itwin/components-react/backport-4.1.0_2023-05-31-10-33.json
- common/changes/@itwin/core-react/backport-4.1.0_2023-05-31-10-33.json
- common/changes/@itwin/imodel-components-react/backport-4.1.0_2023-05-31-10-33.json
- docs/changehistory/4.1.0.md
- ui/appui-layout-react/CHANGELOG.json
- ui/appui-layout-react/CHANGELOG.md
- ui/appui-react/CHANGELOG.json
- ui/appui-react/CHANGELOG.md
- ui/components-react/CHANGELOG.json
- ui/components-react/CHANGELOG.md
- ui/core-react/CHANGELOG.json
- ui/core-react/CHANGELOG.md
- ui/imodel-components-react/CHANGELOG.json
- ui/imodel-components-react/CHANGELOG.md
Backport 4.1.0 changelogs.
N/A
> 4.1.0 changelogs

- common/api/appui-layout-react.api.md
- common/api/appui-react.api.md
- common/api/components-react.api.md
- common/api/core-react.api.md
- common/api/imodel-components-react.api.md
- common/api/summary/appui-layout-react.exports.csv
- common/api/summary/appui-react.exports.csv
- common/api/summary/components-react.exports.csv
- common/api/summary/core-react.exports.csv
- common/api/summary/imodel-components-react.exports.csv
Run `rush extract-api` after adding prettier.
N/A
> Extract API

- common/changes/@itwin/appui-react/update_itwinui_react_2023-06-15-12-26.json
- common/changes/@itwin/components-react/update_itwinui_react_2023-06-15-12-26.json
- common/changes/@itwin/core-react/update_itwinui_react_2023-06-15-12-26.json
- common/changes/@itwin/imodel-components-react/update_itwinui_react_2023-06-15-12-26.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/variants/core-3x/pnpm-lock.yaml
- test-apps/appui-test-app/appui-test-providers/package.json
- test-apps/appui-test-app/connected/package.json
- test-apps/appui-test-app/standalone/package.json
- ui/appui-react/package.json
- ui/components-react/package.json
- ui/core-react/package.json
- ui/imodel-components-react/package.json
Updated @itwin/itwinui-react version to 2.11.6.
closes itwin/presentation#167
N/A
> Update @itwin/itwinui-react version

- common/changes/@itwin/core-react/cherry-5641_2023-06-20-10-35.json
- ui/core-react/src/core-react/contextmenu/ContextSubMenu.tsx
- ui/core-react/src/test/contextmenu/ContextMenu.test.tsx
This PR backports https://github.com/iTwin/itwinjs-core/pull/5641
N/A
> Sub-menu close problem (#5641)

- common/api/core-react.api.md
- common/changes/@itwin/core-react/conditional-icon-comments_2023-06-22-18-54.json
- docs/changehistory/NextVersion.md
- ui/core-react/src/core-react/icons/ConditionalIconItem.tsx
- ui/core-react/src/core-react/utils/IconHelper.tsx
Made a couple of small changes in response to comments made after the ConditionalIconItem PR had merged.
Unit tests and interactive test app.
> ConditionalIconItem changes in response to comments.

- common/api/components-react.api.md
- common/api/summary/components-react.exports.csv
- common/changes/@itwin/components-react/controlled_tree_2023-06-27-08-55.json
- docs/changehistory/NextVersion.md
- ui/components-react/src/components-react.ts
- ui/components-react/src/components-react/tree/controlled/component/NodeContent.tsx
- ui/components-react/src/components-react/tree/controlled/component/TreeNodeRenderer.tsx
- ui/components-react/src/test/tree/controlled/component/NodeContent.test.tsx
Promoted `TreeNodeContent` and `TreeNodeIcon` to public
N/A
> Controlled tree: Promote `TreeNodeContent` and `TreeNodeIcon` to public

- docs/changehistory/4.2.0.md
- docs/changehistory/NextVersion.md
> Run prettier:fix

- common/changes/@itwin/appui-layout-react/changelogs-4.2.0_2023-06-27-15-06.json
- common/changes/@itwin/appui-react/changelogs-4.2.0_2023-06-27-15-06.json
- common/changes/@itwin/components-react/changelogs-4.2.0_2023-06-27-15-06.json
- common/changes/@itwin/core-react/changelogs-4.2.0_2023-06-27-15-06.json
- common/changes/@itwin/imodel-components-react/changelogs-4.2.0_2023-06-27-15-06.json
- docs/changehistory/4.2.0.md
- ui/appui-layout-react/CHANGELOG.json
- ui/appui-layout-react/CHANGELOG.md
- ui/appui-react/CHANGELOG.json
- ui/appui-react/CHANGELOG.md
- ui/components-react/CHANGELOG.json
- ui/components-react/CHANGELOG.md
- ui/core-react/CHANGELOG.json
- ui/core-react/CHANGELOG.md
- ui/imodel-components-react/CHANGELOG.json
- ui/imodel-components-react/CHANGELOG.md
Backport 4.2.0 changelogs.
N/A
> 4.2.0 changelogs

- .devcontainer/Dockerfile
Updated the codespace docker file to use Node 18.
Created a new codespace and ran the build and tests.
> Update codespace setup to use Node 18

- common/changes/@itwin/appui-layout-react/changelogs-4.3.0_2023-07-17-11-52.json
- common/changes/@itwin/appui-react/changelogs-4.3.0_2023-07-17-11-52.json
- common/changes/@itwin/components-react/changelogs-4.3.0_2023-07-17-11-52.json
- common/changes/@itwin/core-react/changelogs-4.3.0_2023-07-17-11-52.json
- common/changes/@itwin/imodel-components-react/changelogs-4.3.0_2023-07-17-11-52.json
- docs/changehistory/4.3.0.md
- docs/changehistory/NextVersion.md
- ui/appui-layout-react/CHANGELOG.json
- ui/appui-layout-react/CHANGELOG.md
- ui/appui-react/CHANGELOG.json
- ui/appui-react/CHANGELOG.md
- ui/components-react/CHANGELOG.json
- ui/components-react/CHANGELOG.md
- ui/core-react/CHANGELOG.json
- ui/core-react/CHANGELOG.md
- ui/imodel-components-react/CHANGELOG.json
- ui/imodel-components-react/CHANGELOG.md
Backport 4.3.0 changelogs. 
N/A
> 4.3.0 changelogs

- common/config/azure-pipelines/jobs/version-bump.yaml
Made a required change for release and master branches to have the same NextVersion.md file contents.
N/A
> Fix NextVersion.md clearing on master

- common/changes/@itwin/components-react/Fix_bug_where_rule_group_operator_is_not_changing_2023-08-04-13-27.json
- docs/changehistory/NextVersion.md
- ui/components-react/src/components-react/filter-builder/FilterBuilderContext.tsx
- ui/components-react/src/components-react/filter-builder/FilterBuilderRuleGroup.tsx
- ui/components-react/src/test/filter-builder/Common.tsx
- ui/components-react/src/test/filter-builder/FilterBuilder.test.tsx
Fixed a bug where the user can't change the rule group operator.
closes iTwin/presentation/issues/199
N/A
> Fix bug where rule group operator is not changing

- common/config/azure-pipelines/jobs/version-bump.yaml
Fix prettier in a change I made directly in Azure Pipelines that didnt validate prettier on commit. My bad.
> Fix version-bump.yaml prettier done on ADO

- common/changes/@itwin/appui-layout-react/changelogs-4.4.0_2023-08-15-18-34.json
- common/changes/@itwin/appui-react/changelogs-4.4.0_2023-08-15-18-34.json
- common/changes/@itwin/components-react/changelogs-4.4.0_2023-08-15-18-34.json
- common/changes/@itwin/core-react/changelogs-4.4.0_2023-08-15-18-34.json
- common/changes/@itwin/imodel-components-react/changelogs-4.4.0_2023-08-15-18-34.json
- docs/changehistory/4.4.0.md
- ui/appui-layout-react/CHANGELOG.json
- ui/appui-layout-react/CHANGELOG.md
- ui/appui-react/CHANGELOG.json
- ui/appui-react/CHANGELOG.md
- ui/components-react/CHANGELOG.json
- ui/components-react/CHANGELOG.md
- ui/core-react/CHANGELOG.json
- ui/core-react/CHANGELOG.md
- ui/imodel-components-react/CHANGELOG.json
- ui/imodel-components-react/CHANGELOG.md
4.4.0 changelogs
Backport 4.4.0 changelogs
N/A
> Backport 4.4.0 changelogs to master

- common/changes/@itwin/appui-react/rm-enzyme_2023-08-31-13-24.json
- common/config/rush/browser-approved-packages.json
- ui/appui-react/src/test/statusbar/StatusBarComposer.test.tsx
Clean-up `browser-approved-packages.json` and remove reference to **enzyme** testing.
N/A
> Clean-up `browser-approved-packages.json`

- common/changes/@itwin/appui-layout-react/changelogs-4.5.0_2023-09-06-18-40.json
- common/changes/@itwin/appui-react/changelogs-4.5.0_2023-09-06-18-40.json
- common/changes/@itwin/components-react/changelogs-4.5.0_2023-09-06-18-40.json
- common/changes/@itwin/core-react/changelogs-4.5.0_2023-09-06-18-40.json
- common/changes/@itwin/imodel-components-react/changelogs-4.5.0_2023-09-06-18-40.json
- docs/changehistory/4.5.0.md
- ui/appui-layout-react/CHANGELOG.json
- ui/appui-layout-react/CHANGELOG.md
- ui/appui-react/CHANGELOG.json
- ui/appui-react/CHANGELOG.md
- ui/components-react/CHANGELOG.json
- ui/components-react/CHANGELOG.md
- ui/core-react/CHANGELOG.json
- ui/core-react/CHANGELOG.md
- ui/imodel-components-react/CHANGELOG.json
- ui/imodel-components-react/CHANGELOG.md
Backport changelogs from release/4.5.0
> Backport 4.5.0 changelogs.

- common/changes/@itwin/components-react/fix_rush_cover_fail_2023-09-25-07-42.json
- ui/components-react/src/components-react/datepicker/DateField.tsx
Ignore if statement for successful `rush cover`
`rush cover`
> Ignore if statement for successful `rush cover`

- common/changes/@itwin/appui-layout-react/raplemie-gripTransitionIssue_2023-10-02-19-37.json
- common/changes/@itwin/appui-layout-react/raplemie-gripTransitionIssue_2023-10-02-20-28.json
- common/changes/@itwin/appui-react/raplemie-gripTransitionIssue_2023-10-02-20-28.json
- common/changes/@itwin/components-react/raplemie-gripTransitionIssue_2023-10-02-20-28.json
- common/changes/@itwin/core-react/raplemie-gripTransitionIssue_2023-10-02-20-28.json
- common/changes/@itwin/imodel-components-react/raplemie-gripTransitionIssue_2023-10-02-20-28.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/variants/core-3x/pnpm-lock.yaml
- docs/changehistory/NextVersion.md
- ui/appui-layout-react/package.json
- ui/appui-layout-react/src/appui-layout-react/widget-panels/Grip.scss
- ui/appui-react/package.json
- ui/components-react/package.json
- ui/core-react/package.json
- ui/imodel-components-react/package.json
Add a delay to the grip movement so the grips stop flickering.
Update chai.js to fix npm audit issue.
Ran unit test, tested solution in DR manually (could not reproduce in test apps)
resolves #443
> Fix grips flickers + AUDIT FIX

- common/config/rush/browser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/variants/core-3x/pnpm-lock.yaml
- docs/storybook/package.json
- docs/storybook/src/components/FilterBuilder.stories.tsx
- docs/storybook/src/components/FilterBuilder.tsx
- docs/storybook/vite.config.ts
Added stories for `FilterBuilder` component to the storybook.
Setup storybook to copy locales from `components-react` and `core-react` packages to make sure that strings in stories are localized.
N/A
> Add FilterBuilder component story to storybook

- .github/workflows/publish-storybook.yaml
Exclude only root `index.html` when cleaning `gh-pages`.
N/A
> Exclude only root `index.html`

- test-apps/appui-test-app/appui-test-providers/src/ui/widgets/SelectedElementDataWidget.tsx
Changed the mounting value so when there are selected elements when opening the frontstage, the widget will actually display directly, instead of requiering to unselect and reselect elements.
N/A
> Improve SelectedElementDataWidget

- docs/changehistory/NextVersion.md
> Fix nextVersion

- common/changes/@itwin/appui-react/raplemie-fixSettingsSaveEffect_2023-11-20-18-09.json
- full-stack-tests/ui/tests/popout-widget.test.ts
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
Add proper dependency array to save. Might fix CI e2e test (issue not present locally, but this may affect it)
Ran test locally... (but it was already working before, locally...)
> Fix setting save effect dependency

- common/changes/@itwin/appui-react/raplemie-GetStartedFeatureDocumentation_2023-11-24-19-38.json
- ui/appui-react/src/appui-react/UiFramework.ts
- ui/appui-react/src/appui-react/accudraw/FrameworkAccuDraw.ts
- ui/appui-react/src/appui-react/messages/AppNotificationManager.ts
- ui/appui-react/src/appui-react/safearea/SafeAreaContext.tsx
- ui/appui-react/src/appui-react/theme/ThemeManager.tsx
- ui/appui-react/src/appui-react/tools/FrameworkToolAdmin.ts
- ui/appui-react/src/appui-react/uiadmin/FrameworkUiAdmin.tsx
- ui/appui-react/src/appui-react/uistate/useUiStateStorage.tsx
Added/unified some classes documentation to explain their expected use and example usage. Expanding on #573 to facilitate learning.
N/A
> Added expected usage in documentation for some classes.

- common/api/appui-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/raplemie-frameworkToolAdminBeta_2023-12-05-21-16.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/tools/FrameworkToolAdmin.ts
Promoted `FrameworkToolAdmin` to _beta_. This is our solution so `UiFramework.keyboardShortcuts` acutally do anything, and currently it is _alpha_, so invisible in the documentation.
N/A
Resolves #464
> Promote `FrameworkToolAdmin` to _beta_

- common/changes/@itwin/components-react/filter-builder-default-operator_2023-12-06-09-47.json
- docs/changehistory/NextVersion.md
- ui/components-react/src/components-react/filter-builder/FilterBuilderState.ts
- ui/components-react/src/test/filter-builder/FilterBuilderState.test.ts
Change the behavior of property setting for rule item to reset operator on change.
Added a test case where property is changed for the same rule item.
> Change behavior of property setting in Filter State

- README.md
Added a line in README that the "rush cover" actually creates a complete HTML report, that was not obvious and caused some wasted time.
N/A
> Augment README with HTML coverage report location.

- common/changes/@itwin/appui-react/raplemie-reparentingRevert_2023-12-20-14-03.json
- docs/changehistory/NextVersion.md
- full-stack-tests/ui/tests/popout-widget.test.ts
- ui/appui-react/src/appui-react/childwindow/InternalChildWindowManager.tsx
- ui/appui-react/src/appui-react/childwindow/PopoutWidget.tsx
- ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
- ui/appui-react/src/test/childwindow/PopoutWidget.test.snap
- ui/appui-react/src/test/childwindow/PopoutWidget.test.tsx
Reverted changes #606 
Validated with tests, and manually, the behavior is back.
Workaround #632, Reopens #524
> Revert popout reparenting

- common/scripts/create_release.py
Fix changelog link from `itwinjs-core` to `appui`
N/A
Resolves #646
> Fix changelog link

- common/changes/@itwin/appui-layout-react/changelogs-4.7.2_2023-12-21-17-14.json
- common/changes/@itwin/appui-react/changelogs-4.7.2_2023-12-21-17-14.json
- common/changes/@itwin/components-react/changelogs-4.7.2_2023-12-21-17-14.json
- common/changes/@itwin/core-react/changelogs-4.7.2_2023-12-21-17-14.json
- common/changes/@itwin/imodel-components-react/changelogs-4.7.2_2023-12-21-17-14.json
- ui/appui-layout-react/CHANGELOG.json
- ui/appui-layout-react/CHANGELOG.md
- ui/appui-react/CHANGELOG.json
- ui/appui-react/CHANGELOG.md
- ui/components-react/CHANGELOG.json
- ui/components-react/CHANGELOG.md
- ui/core-react/CHANGELOG.json
- ui/core-react/CHANGELOG.md
- ui/imodel-components-react/CHANGELOG.json
- ui/imodel-components-react/CHANGELOG.md
Backport 4.7.2 changelogs.
N/A
> 4.7.2 changelogs

- common/changes/@itwin/appui-layout-react/changelogs-4.8.0_2023-12-21-19-20.json
- common/changes/@itwin/appui-react/changelogs-4.8.0_2023-12-21-19-20.json
- common/changes/@itwin/components-react/changelogs-4.8.0_2023-12-21-19-20.json
- common/changes/@itwin/core-react/changelogs-4.8.0_2023-12-21-19-20.json
- common/changes/@itwin/imodel-components-react/changelogs-4.8.0_2023-12-21-19-20.json
- docs/changehistory/4.8.0.md
- ui/appui-layout-react/CHANGELOG.json
- ui/appui-layout-react/CHANGELOG.md
- ui/appui-react/CHANGELOG.json
- ui/appui-react/CHANGELOG.md
- ui/components-react/CHANGELOG.json
- ui/components-react/CHANGELOG.md
- ui/core-react/CHANGELOG.json
- ui/core-react/CHANGELOG.md
- ui/imodel-components-react/CHANGELOG.json
- ui/imodel-components-react/CHANGELOG.md
Backport 4.8.0 changelogs.
N/A
> 4.8.0 changelogs

- README.md
- test-apps/appui-test-app/connected/README.md
- test-apps/appui-test-app/standalone/README.md
Added `Testing options` section to the readme, mainly to have somewhere to put the Storybook starting command and raise some awareness about it :)
N/A
> Adding Testing options info to README (test-apps/storybook)

- common/changes/@itwin/appui-layout-react/raplemie-previewFeatureDiscussionsLinks_2024-01-12-21-38.json
- common/config/rush/variants/core-3x/pnpm-lock.yaml
- ui/appui-layout-react/src/appui-layout-react/preview/PreviewFeatures.tsx
Discussions were enabled to get feedbacks from the users about preview features, adding a link in the JSDOC so there is at least one place a dev can discover this by himself.
N/A
> Provide discussion links for preview features

- .vscode/settings.json
Auto-update vscode settings https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto
N/A
> Auto update vscode settings

- common/changes/@itwin/appui-react/changelogs-4.9.0_2024-02-06-11-14.json
- common/changes/@itwin/components-react/changelogs-4.9.0_2024-02-06-11-14.json
- common/changes/@itwin/core-react/changelogs-4.9.0_2024-02-06-11-14.json
- common/changes/@itwin/imodel-components-react/changelogs-4.9.0_2024-02-06-11-14.json
- docs/changehistory/4.9.0.md
- ui/appui-react/CHANGELOG.json
- ui/appui-react/CHANGELOG.md
- ui/components-react/CHANGELOG.json
- ui/components-react/CHANGELOG.md
- ui/core-react/CHANGELOG.json
- ui/core-react/CHANGELOG.md
- ui/imodel-components-react/CHANGELOG.json
- ui/imodel-components-react/CHANGELOG.md
Backport 4.9.0 changelogs.
N/A
> 4.9.0 changelogs

- common/config/rush/pnpm-config.json
Ignore CVE until ip or storybook fixes it.
N/A
> Ignore CVE-2023-42282

- common/changes/@itwin/appui-react/move-under-preview_2024-03-20-11-38.json
- ui/appui-react/src/appui-react/layout/StandardLayout.tsx
- ui/appui-react/src/appui-react/preview/PreviewFeatures.tsx
- ui/appui-react/src/appui-react/preview/activate-dropped-tab/activateDroppedTab.ts
- ui/appui-react/src/appui-react/preview/content-always-max-size/useContentAlwaysMaxSize.scss
- ui/appui-react/src/appui-react/preview/content-always-max-size/useContentAlwaysMaxSize.tsx
- ui/appui-react/src/appui-react/preview/enable-maximized-widget/useMaximizedWidget.scss
- ui/appui-react/src/appui-react/preview/enable-maximized-widget/useMaximizedWidget.tsx
- ui/appui-react/src/appui-react/preview/horizontal-panel-alignment/useHorizontalPanelAlignment.scss
- ui/appui-react/src/appui-react/preview/horizontal-panel-alignment/useHorizontalPanelAlignment.tsx
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
- ui/appui-react/src/test/preview/activate-dropped-tab/activateDroppedTab.test.ts
Move preview features under preview dir. #710
N/A
> maintenance: move preview features under preview dir

- common/changes/@itwin/appui-react/changelogs-4.12.0_2024-04-05-11-58.json
- common/changes/@itwin/components-react/changelogs-4.12.0_2024-04-05-11-58.json
- common/changes/@itwin/core-react/changelogs-4.12.0_2024-04-05-11-58.json
- common/changes/@itwin/imodel-components-react/changelogs-4.12.0_2024-04-05-11-58.json
- docs/changehistory/4.12.0.md
- ui/appui-react/CHANGELOG.json
- ui/appui-react/CHANGELOG.md
- ui/appui-react/src/test/content/ContentLayout.test.tsx
- ui/components-react/CHANGELOG.json
- ui/components-react/CHANGELOG.md
- ui/components-react/src/test/tree/controlled/internal/SparseTree.test.ts
- ui/core-react/CHANGELOG.json
- ui/core-react/CHANGELOG.md
- ui/imodel-components-react/CHANGELOG.json
- ui/imodel-components-react/CHANGELOG.md
Backport 4.12.0 changelogs.
N/A
> 4.12.0 changelogs

- common/api/appui-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/public-floating-viewport-content-wrapper_2024-04-10-11-32.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/content/FloatingViewportContent.tsx
Bumped `FloatingViewportContentWrapper` to `@public`.
N/A
> Public floating viewport content wrapper

- common/api/core-react.api.md
- common/api/summary/core-react.exports.csv
- common/changes/@itwin/core-react/public-use-cross-origin-popup_2024-04-10-11-51.json
- docs/changehistory/NextVersion.md
- ui/core-react/src/core-react/utils/hooks/useCrossOriginPopup.tsx
Bumped `useCrossOriginPopup` to `@public`.
N/A
> Bump `useCrossOriginPopup` to `@public`.

- common/changes/@itwin/core-react/fix-docs_2024-04-24-08-08.json
- ui/core-react/src/core-react/button/UnderlinedButton.tsx
> Fix docs issue

- common/changes/@itwin/core-react/card-story_2024-04-30-10-02.json
- docs/storybook/src/components/CardPopup.stories.tsx
- docs/storybook/src/components/CardPopup.tsx
- docs/storybook/src/components/RadialMenu.stories.tsx
- ui/core-react/src/core-react/radialmenu/Annulus.ts
- ui/core-react/src/core-react/radialmenu/RadialMenu.tsx
This PR adds `CardPopup` and `RadialMenu` stories.
N/A
> Add `CardPopup` and `RadialMenu` stories

- common/changes/@itwin/core-react/context-menu_2024-05-09-07-44.json
- docs/changehistory/NextVersion.md
- docs/storybook/src/components/ContextMenu.stories.tsx
- ui/core-react/src/core-react/contextmenu/ContextMenu.scss
- ui/core-react/src/core-react/contextmenu/ContextMenu.tsx
- ui/core-react/src/core-react/contextmenu/ContextSubMenu.tsx
This PR fixes:
- SVG icon alignment in `ContextMenuItem` component.
- `ContextSubMenu` to correctly render provided SVG icon.
Added additional story.
> Fix SVG icon alignment in `ContextMenuItem`

- common/changes/@itwin/imodel-components-react/add-button-label-settings-translation_2024-05-16-17-17.json
- ui/imodel-components-react/src/imodel-components-react/UiIModelComponents.json
- ui/imodel-components-react/src/imodel-components-react/timeline/SolarTimeline.tsx
- ui/imodel-components-react/src/imodel-components-react/timeline/TimelineComponent.tsx
This PR adds `button.label.settings` as a translation option in UiIModelComponents.json. This PR addresses Issue #841 
N/A
> Added button.label.settings Translation to UiIModelComponents.json

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/issue-862_2024-06-11-10-22.json
- common/config/rush/pnpm-lock.yaml
- test-apps/appui-test-app/appui-test-providers/src/ui/dialogs/PopupTestView.tsx
- ui/appui-react/src/appui-react/configurableui/ConfigurableUiContent.scss
- ui/appui-react/src/appui-react/feedback/ElementTooltip.scss
- ui/appui-react/src/appui-react/feedback/ElementTooltip.tsx
This PR fixes #862 
The class component is refactored to a function component.
Updated `PopupTestView` of a test app.
> Fix `ElementTooltip` to correctly render in a popup window

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/fix-old-deprecations_2024-07-10-09-22.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/cursor/cursorpopup/CursorPopup.tsx
- ui/appui-react/src/appui-react/popup/CardPopup.tsx
- ui/appui-react/src/appui-react/popup/PopupManager.tsx
- ui/appui-react/src/appui-react/popup/ToolbarPopup.tsx
- ui/appui-react/src/appui-react/redux/SessionState.ts
- ui/appui-react/src/appui-react/uiadmin/FrameworkUiAdmin.tsx
This PR fixes some old deprecations that were not used correctly and therefore apis were not marked as deprecated.
N/A
> Fix old deprecations

- common/changes/@itwin/appui-react/deprecate-theme-manager_2024-09-13-06-43.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/theme/ThemeManager.tsx
This PR explicitly deprecates CSS and SCSS variables.
N/A
> Deprecate `--buic` CSS variables

- common/changes/@itwin/appui-react/changelogs-4.17.0_2024-09-19-14-24.json
- common/changes/@itwin/components-react/changelogs-4.17.0_2024-09-19-14-24.json
- common/changes/@itwin/core-react/changelogs-4.17.0_2024-09-19-14-24.json
- common/changes/@itwin/imodel-components-react/changelogs-4.17.0_2024-09-19-14-24.json
- docs/changehistory/4.17.0.md
- ui/appui-react/CHANGELOG.json
- ui/appui-react/CHANGELOG.md
- ui/components-react/CHANGELOG.json
- ui/components-react/CHANGELOG.md
- ui/core-react/CHANGELOG.json
- ui/core-react/CHANGELOG.md
- ui/imodel-components-react/CHANGELOG.json
- ui/imodel-components-react/CHANGELOG.md
Backport 4.17.0 changelogs.
N/A
> 4.17.0 changelogs

- apps/test-app/package.json
- common/changes/@itwin/appui-react/fix-start_2024-09-27-08-21.json
- common/changes/@itwin/components-react/fix-start_2024-09-27-08-21.json
- common/changes/@itwin/core-react/fix-start_2024-09-27-08-21.json
- common/changes/@itwin/imodel-components-react/fix-start_2024-09-27-08-21.json
- common/scripts/package-cjs.mjs
- ui/appui-react/package.json
- ui/components-react/package.json
- ui/core-react/package.json
- ui/imodel-components-react/package.json
This PR fixes `start` scripts to correctly start the watch mode which was broken by #1048
N/A
> Fix `start` scripts

- common/api/appui-react.api.md
- common/api/components-react.api.md
- common/api/summary/appui-react.exports.csv
- common/api/summary/components-react.exports.csv
- common/changes/@itwin/appui-react/drop-react17_2024-09-27-11-04.json
- common/changes/@itwin/components-react/drop-react17_2024-09-27-11-04.json
- common/changes/@itwin/core-react/drop-react17_2024-09-27-11-04.json
- common/changes/@itwin/imodel-components-react/drop-react17_2024-09-27-11-04.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- docs/changehistory/NextVersion.md
- ui/appui-react/package.json
- ui/appui-react/src/appui-react/childwindow/InternalChildWindowManager.tsx
- ui/appui-react/src/appui-react/framework/FrameworkChildWindows.ts
- ui/appui-react/src/appui-react/hooks/useActiveViewport.tsx
- ui/appui-react/src/appui-react/hooks/useAnalysisAnimationDataProvider.tsx
- ui/appui-react/src/appui-react/hooks/useConditionalProp.tsx
- ui/appui-react/src/appui-react/hooks/useScheduleAnimationDataProvider.tsx
- ui/appui-react/src/appui-react/uistate/useReduxFrameworkState.tsx
- ui/appui-react/src/test/layout/Utils.tsx
- ui/appui-react/src/test/layout/widget-panels/Grip.test.tsx
- ui/appui-react/src/test/layout/widget-panels/usePanelsAutoCollapse.test.tsx
- ui/appui-react/src/test/layout/widget/PanelWidget.test.tsx
- ui/components-react/package.json
- ui/components-react/src/components-react/favorite/FavoritePropertiesRenderer.ts
- ui/components-react/src/components-react/toolbar/InternalToolbarComponent.tsx
- ui/components-react/src/test/favorite/FavoritePropertiesRenderer.test.tsx
- ui/core-react/package.json
- ui/imodel-components-react/package.json
This PR fixes #786 by dropping support for React 17.x.
N/A
> Drop support for React 17.x

- docs/changehistory/NextVersion.md
This PR fixes a link in `NextVersion.md` and reduces the usage of bold font.
N/A
> Fix a link in NextVersion.md

- common/changes/@itwin/appui-react/fix-message-box_2024-11-08-10-55.json
- ui/appui-react/src/appui-react/dialog/StandardMessageBox.tsx
This PR fixes localization of `StandardMessageBox` component.
N/A
> Fix localization of `StandardMessageBox` component

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/remove-internal-tag-from-widgetdef-defaultstate_2024-12-04-19-17.json
- ui/appui-react/src/appui-react/widgets/WidgetDef.tsx
Removed `@internal` from `WidgetDef.defaultState`.
resolves #1140
N/A
> WidgetDef.defaultState no longer internal

- docs/storybook/src/Introduction.mdx
This PR fixes storybook links.
N/A
> Fix storybook links

- common/changes/@itwin/appui-react/JonasD-remove-core-telemetry_2025-01-31-10-56.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- ui/appui-react/package.json
Removed unnecessary @itwin/core-telemetry devDependency from @itwin/appui-react
> Remove @itwin/core-telemetry from @itwin/appui-react devDependencies

- common/config/azure-pipelines/jobs/docs-ci.yaml
> update docs agent pool

- common/changes/@itwin/core-react/bump-dompurify_2025-02-25-13-16.json
- common/config/rush/pnpm-lock.yaml
- docs/changehistory/NextVersion.md
- ui/core-react/package.json
- ui/core-react/src/core-react/icons/IconComponent.tsx
- ui/core-react/src/core-react/notification/MessageRenderer.tsx
- ui/core-react/src/core-react/utils/IconWebComponent.ts
Fixes #1230 by bumping the `dompurify` version.
N/A
> Update `dompurify` version

- common/changes/@itwin/components-react/skip-flaky-test_2025-04-08-12-42.json
- ui/components-react/src/test/tree/controlled/internal/SparseTree.test.ts
This PR skips flaky test which is causing issues in CI pipelines.
N/A
> Skip flaky test

- apps/test-app/package.json
- docs/storybook/package.json
- docs/storybook/vite.config.ts
- pnpm-lock.yaml
Fix `pnpm audit` due to https://github.com/advisories/GHSA-67mh-4wv8-2f99
Bumped `vite` and removed `vite-plugin-commonjs`.
Tested storybook locally.
> Fix `pnpm audit`

- .github/workflows/CI.yaml
- ui/appui-react/src/appui-react.ts
Fix `extract-api` on CI to fail the build.
N/A
> Extract API to fail build

- .github/workflows/changeset-release.yaml
Fix release again by re-adding `id-token`.
N/A
> Re-fix release

- pnpm-lock.yaml
This PR fixes `pnpm audit` failure due to https://github.com/advisories/GHSA-v6h2-p8h4-qcjw
N/A
> Bump `brace-expansion`

- .changeset/lovely-baths-strive.md
Mark changeset of https://github.com/iTwin/appui/pull/1343 as `patch` instead of `minor`.
N/A
> Mark changeset as `patch`

- pnpm-lock.yaml
Bumped `form-data` version to make sure `pnpm audit` passes.
N/A
> Bump form-data version

- common/api/appui-react.api.md
- ui/appui-react/src/appui-react/widgets/WidgetState.ts
Update inline documentation of `WidgetState` enum based on https://github.com/iTwin/appui/discussions/1385#discussioncomment-14073551
N/A
> Update `WidgetState` docs

- apps/test-app/package.json
- pnpm-lock.yaml
This PR updates `electron` version and fixes `https://github.com/advisories/GHSA-vmqv-hx8q-j7mg`
N/A
> Update `electron` version

- .changeset/mighty-clocks-sleep.md
- ui/imodel-components-react/src/imodel-components-react/inputs/new-editors/UseQuantityInfo.ts
Fixes https://github.com/iTwin/presentation/issues/1056 in new editors system.
Tested manually.
Before:
After:
> Increase KOQ editor precision
