- changehistory/NextVersion.md
- common/api/appui-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/status-bar-field_2023-03-21-14-53.json
- ui/appui-react/src/appui-react/statusbar/Field.scss
- ui/appui-react/src/appui-react/statusbar/Field.tsx
- ui/appui-react/src/appui-react/statusbar/Indicator.tsx
- ui/appui-react/src/appui-react/statusbar/Popup.tsx
- ui/appui-react/src/appui-react/statusbar/StatusBar.tsx
- ui/appui-react/src/appui-react/statusfields/SectionsField.tsx
- ui/appui-react/src/test/statusfields/SnapMode.test.tsx
Existing `StatusBarIndicator` container component is easy to use, but not as configurable for advanced use cases, where more control is needed over popup i.e. for nested popups, outside click events or popup state management.
This PR exposes `StatusBar.Field` and `StatusBar.Popup` components to facilitate building such custom status bar indicators.
> Expose StatusBar.Field and StatusBar.Popup components

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/feat-feature-overrides-uievent_2023-04-04-15-00.json
- ui/appui-react/src/appui-react/syncui/SyncUiEventDispatcher.ts
In SyncUIEventDispatcher, there are currently no SyncUIEvent that listens to when a feature override is applied/removed.
Add FeatureOverridesChanged in SyncUIEventIds and add a listener to the viewport's onFeatureOverridesChanged event.
manually merges changes from [Add FeatureOverridesChanged SyncUIEvent to SyncUIEventDispatcher #4529](https://github.com/iTwin/itwinjs-core/pull/4529)
> Add FeatureOverridesChanged SyncUIEvent to SyncUIEventDispatcher

- common/changes/@itwin/components-react/fix_property_grid_expanders_2023-04-05-11-06.json
- ui/components-react/src/components-react/properties/renderers/label/NonPrimitivePropertyLabelRenderer.tsx
- ui/components-react/src/components-react/properties/renderers/label/PropertyLabelRenderer.scss
- ui/components-react/src/test/properties/renderers/label/PropertyLabelRenderer.test.tsx
Fixed style of non primitive property expander.
Before:
After:
> PropertyGrid: Fix non primitive property expander

- common/api/appui-react.api.md
- common/api/components-react.api.md
- common/api/summary/appui-react.exports.csv
- common/api/summary/components-react.exports.csv
- common/changes/@itwin/appui-codemod/move-toolbar_2023-04-07-14-50.json
- common/changes/@itwin/appui-react/move-toolbar_2023-04-07-14-50.json
- common/changes/@itwin/components-react/move-toolbar_2023-04-07-14-50.json
- docs/changehistory/NextVersion.md
- tools/codemod/src/v4.0.0/__testfixtures__/full.input.tsx
- tools/codemod/src/v4.0.0/__testfixtures__/full.output.tsx
- tools/codemod/src/v4.0.0/__tests__/components-react.test.ts
- tools/codemod/src/v4.0.0/components-react.ts
- tools/codemod/src/v4.0.0/full.ts
- ui/appui-react/src/appui-react.ts
- ui/appui-react/src/appui-react/popup/CardPopup.tsx
- ui/appui-react/src/appui-react/popup/ToolbarPopup.tsx
- ui/appui-react/src/appui-react/toolbar/Toolbar.tsx
- ui/appui-react/src/appui-react/toolbar/ToolbarComposer.tsx
- ui/appui-react/src/appui-react/toolbar/ToolbarWithOverflow.tsx
- ui/appui-react/src/appui-react/toolbar/toUIAToolbarItem.ts
- ui/components-react/src/components-react/toolbar/Toolbar.tsx
- ui/components-react/src/components-react/toolbar/ToolbarWithOverflow.tsx
- ui/components-react/src/test/toolbar/Toolbar.test.tsx
- ui/components-react/src/test/toolbar/ToolbarWithOverflow.test.tsx
This PR moves `Toolbar` components from **@itwin/components-react** to **@itwin/appui-react**. Moved components are deprecated in the `@itwin/components-react` package. Codemod is also provided to facilitate the change.
> Move Toolbar components to @itwin/appui-react

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/fix-selection-scope-field_2023-04-11-07-43.json
- docs/changehistory/NextVersion.md
- test-apps/appui-test-app/standalone/src/frontend/index.tsx
- tools/internal/scripts/rush/audit.js
- ui/appui-react/public/locales/en/UiFramework.json
- ui/appui-react/src/appui-react/statusfields/SelectionScope.tsx
- ui/appui-react/src/test/statusfields/SelectionScope.test.tsx
This PR converts `SelectionScopeField` to a function component and fixes an issue with stale options of a `Select`.
Fallback labels defined in `selectionScopeLabels` are removed, since labels are provided by `presentation` layer.
> Fix selection scope field

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/raplemie-snapModeDispatchSyncEvent_2023-04-11-19-42.json
- ui/appui-react/src/appui-react/statusfields/SnapMode.tsx
- ui/appui-react/src/test/statusfields/SnapMode.test.tsx
To follow `SelectionScopeField` and allow tracking, `SnapModeField` now emits a `SyncEvent` (which already existed)
> Emit syncEvent on snap mode change

- common/config/azure-pipelines/jobs/version-bump.yaml
This PR adds missing `version-policy` argument to `rush version --bump` script.
> Add missing version-policy argument

- common/changes/@itwin/appui-react/cleanup_localized_strings_2023-04-20-15-54.json
- ui/appui-react/public/locales/en/UiFramework.json
Remove unused visibility widget localized strings. They were moved to [tree-widget-react](https://github.com/iTwin/viewer-components-react/blob/master/packages/itwin/tree-widget/public/locales/en/TreeWidget.json) package.
> Cleanup unused localized strings

- common/changes/@itwin/appui-react/fix-selection-info_2023-04-24-08-45.json
- ui/appui-react/src/appui-react/syncui/SyncUiEventDispatcher.ts
Dispatch `SetNumItemsSelected` action when selection set changes.
This fixes `SelectionInfoField` component by displaying selection set size. 
Tested via standalone appui-test-app.
> Fix `SelectionInfoField` by displaying selection set size

- common/changes/@itwin/appui-react/raplemie-toolAssistanceImages_2023-05-11-18-56.json
- ui/appui-react/src/appui-react/statusfields/toolassistance/ToolAssistanceField.tsx
- ui/appui-react/src/test/statusfields/toolassistance/ToolAssistanceField.test.tsx
If the provided instruction.image is not identified as an svg component, use its value as a string, which is likely a webfont class name. (As was prior behavior in 3.x)
Added a test that validates that a string not starting with `webSvg:` will be used as a class name on an instruction.
Validated visually that the fix worked in test app.
resolves #303
> Fix ToolAssistanceField icon display

- common/api/appui-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/selection-count_2023-05-18-13-47.json
- ui/appui-react/package.json
- ui/appui-react/src/appui-react.ts
- ui/appui-react/src/appui-react/statusfields/SelectionCount.scss
- ui/appui-react/src/appui-react/statusfields/SelectionCount.tsx
- ui/appui-react/src/appui-react/statusfields/SelectionInfo.tsx
- ui/appui-react/src/appui-react/ui-items-provider/StandardStatusbarUiItemsProvider.tsx
- ui/appui-react/src/test/TestUtils.ts
- ui/appui-react/src/test/statusfields/SelectionInfo.test.tsx
This PR adds a `SelectionCountField` component. This controlled component can be used instead of an existing redux-connected `SelectionInfoField`.
Updated unit tests.
Ran the standalone test app to verify.
> Add SelectionCountField component

- common/changes/@itwin/components-react/Fix_tree_flickering_without_keeping_scrollbar_2023-05-22-07-42.json
- ui/components-react/src/components-react/tree/controlled/component/ControlledTree.scss
- ui/components-react/src/components-react/tree/controlled/component/TreeRenderer.tsx
- ui/components-react/src/test/tree/controlled/component/TreeRenderer.test.tsx
Previously, we were keeping our horizontal scrollbar width to avoid this issue: https://github.com/bvaughn/react-window/issues/681, which can lead to behaviour, where we show horizontal scrollbar, even though there is plenty room for the data
For example: 
closes itwin/viewer-components-react#500
N/A
> Fix tree flickering without keeping horizontal scrollbar

- common/config/azure-pipelines/jobs/version-bump.yaml
The version bump pipeline, with `releaseCandidate` type, will now create a commit on master that will not trigger a nightly build publishing. (When we created the branch for 4.0.0, packages 4.1.0-dev.0 were published on npm, that was not intended, and caused confusion as the 4.1.0 was not in the work at all and we didnt publish any nightlies after that.)
https://www.npmjs.com/package/@itwin/appui-react/v/4.1.0-dev.0
No tests were done, we should see if it works when we create the RC for 4.1.0.
> Do not publish nightly `dev.0` after RC creation.

- .github/workflows/finalize-release.yaml
The "Finalize-release.yaml" script is taking care of porting back the changes from the release branch back to master (changelogs) and currently failed.
This script is trying to handle "backports" changes even if none were actually created, and this makes the `git add` command crash because it tries to add nothing. While the script itself is set up to handle such failure, the git command itself abort the whole command, also not adding the existing file change.
This attempt at adressing this by splitting the "always there" files and the "maybe there" files (which can fail without breaking the script)
Tested manually the commands and validated the error, however, I'll only see once the action triggers if it works correctly within the CI environment.
> Succeed even if no backported changes exists.

- common/changes/@itwin/appui-react/raplemie-ThemeManager_2023-06-13-15-44.json
- ui/appui-react/src/appui-react/theme/ThemeManager.tsx
- ui/appui-react/src/test/theme/ThemeManager.test.tsx
Removing a `ref` that was added for the iTwinUI 1.0 `ThemeProvider` and that is no longer needed with 2.0.
Improved testing so they actually test the component effect rather than only the store handling.
Removing the `ref` caused the component to no longer refresh on initial loading, requiring the `componentMounted` to be expanded so the opacities were also applied.
Improved tests to validate proper application of changes, validated through test app that the behavior was correct.
Resolves #179
> Clean `ThemeManager` and improve tests

- common/changes/@itwin/appui-react/raplemie-improveToUIAToolbarItem_2023-06-14-19-51.json
- test-apps/appui-test-app/appui-test-providers/src/ui/providers/CustomContentStageUiProvider.tsx
- test-apps/appui-test-app/appui-test-providers/src/ui/providers/MessageUiItemsProvider.tsx
- ui/appui-react/src/appui-react/toolbar/toUIAToolbarItem.ts
Improves internal function to take into account groups and missing `badgeType` conversion, however, this seems like this process was meant to be updated and maybe forgotten, so @GerardasB can you confirm what was the plan ? 
Added 2 badges in our test apps so we actually see them somewhere, one in action, one in a group.
resolves #361
> Add `badgeType` to all items and handle group `items`

- common/changes/@itwin/appui-react/raplemie-dialogManagersCloseAll_2023-06-09-18-43.json
- ui/appui-react/src/appui-react/dialog/InternalContentDialogManager.tsx
- ui/appui-react/src/appui-react/dialog/InternalModelessDialogManager.tsx
- ui/appui-react/src/test/dialog/ContentDialogManager.test.tsx
- ui/appui-react/src/test/dialog/ModelessDialogManager.test.tsx
resolves #147 
Completely clean `InternalContentDialogManager` and `InternalModelessDialogManager` when `closeAll` is called.
This method is internal and only used in tests.
Added failing tests that pointed out the issues and ensured they now passed.
> Fix and test `closeAll` methods

- common/changes/@itwin/appui-layout-react/raplemie-popoutsLocation_2023-06-22-17-07.json
- common/changes/@itwin/appui-react/raplemie-popoutsLocation_2023-06-22-17-07.json
- ui/appui-layout-react/src/appui-layout-react/state/NineZoneState.ts
- ui/appui-react/src/appui-react/childwindow/InternalChildWindowManager.tsx
Modified `adjustWindowLocation` private method of `InternalChildWindowManager` to not use `window.top` properties.
Removed dead code from the private function that was never called.
resolves #379 
Removed a `contain` in appui-layout-react that was unexpectedly trying to contain popped out wigets, now the widget will reappear where they were last closed by the user.
resolves #381 
Using `pagehide` event handler instead of `onbeforeunload` for firefox and overall posible better results.
resolves #380 
Visual/Manual testing through `test-apps/standalone` (web)
> Fix popout location

- common/api/components-react.api.md
- common/changes/@itwin/components-react/controlled_tree_js_fix_2023-07-03-14-43.json
- ui/components-react/src/components-react/tree/controlled/internal/SparseTree.ts
`SparseArray` class has two symbol properties defined: `immerable` and `Symbol.iterator`. For some reason compiled javascript looks like this:
```typescript
var _b;
export class SparseArray {
constructor() {
this[_b] = true;
// ...
}
[(_b = immerable, Symbol.iterator)]() {
// ...
}
}
```
This causes some problems for terser when minimizing code and removing dead code to reduce bundle size. Minimized code looks like this:
```javascript
(_b = lC), Symbol.iterator;
```
Which under `"use strict"` mode throws runtime error because `_b` is not defined: https://github.com/iTwin/viewer/issues/283
Setting `immerable` property value in constructor seems to result in cleaner compiled javascript code which does not cause problems for terser:
Compiled javascript code:
```typescript
export class …
```
> ControlledTree: cleanup copiled SparseTree code

- common/config/azure-pipelines/jobs/version-bump.yaml
- docs/changehistory/NextVersion.md
- NextVersion.md file now ignores first TOC element.
- Version bump powershell script for NextVersion.md now correctly formats following version .md and new NextVersion.md files.
Ran script locally to check if prettier still complains about formatting.
> Fix pipeline formatting mismatch for NextVersion.md

- common/config/azure-pipelines/jobs/version-bump.yaml
- docs/changehistory/4.0.0.md
- docs/changehistory/4.1.0.md
- docs/changehistory/4.2.0.md
- docs/changehistory/4.3.0.md
- docs/changehistory/NextVersion.md
Removed legacy frontmatter from NextVersion.md and 4.x.x.md files and updated pipeline to reflect changes.
Locally ran PowerShell scripts to confirm correct behavior.
> Remove frontmatter from version markdown files

- common/config/azure-pipelines/jobs/docs-ci.yaml
Change the pipeline to add `hasDocs` tag on the docs if these should be published (only when releasing a new package)
None
> Add `hasDocs` on release version bumps commits

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/fix-clear-hide-desync_2023-07-25-12-58.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/selection/HideIsolateEmphasizeManager.ts
- ui/appui-react/src/appui-react/selection/SelectionContextItemDef.ts
- ui/appui-react/src/appui-react/syncui/SyncUiEventDispatcher.ts
- ui/appui-react/src/test/widgets/BasicToolWidget.test.tsx
Buttons `clearHideIsolateEmphasizeElements` and `hideElements` now display correctly* when individual elements' visibility in the view is toggled.
*`clearHideIsolateEmphasizeElements` button should not be displayed if no element in the current view is hidden. `hideElements` button should only be displayed if elements in the active selection (if one exists) are not hidden.
Set up a cospace with viewer-components-react & appui and tested button updating their states while toggling individual element visibility from Models Tree.
> Fix desynced element hiding and clearing

- docs/changehistory/4.0.0.md
Updated the @bentley/icons-generic-webfont section of the 4.0.0 changehistory file to provide improved instructions for applications that need to continue to use the webfont.
> Improve instructions for apps to use icons webfont

- common/changes/@itwin/appui-react/fix-toolbar-doc_2023-07-27-21-54.json
- ui/appui-react/src/appui-react/toolbar/ToolbarItem.ts
A colleague from User Success pointed out that we are using the obsolete term "ninezone" in our toolbar documentation. Changed the comment to be harvested into the API docs to read "AppUI."
> Fix toolbar doc

- test-apps/appui-test-app/connected/src/frontend/appui/ExternalIModel.ts
- test-apps/appui-test-app/connected/src/frontend/index.tsx
- test-apps/appui-test-app/standalone/src/frontend/appui/LocalFileSupport.ts
- test-apps/appui-test-app/standalone/src/frontend/appui/frontstages/LocalFileStage.tsx
- test-apps/appui-test-app/standalone/src/frontend/index.tsx
Brien pointed out that when creating the new test apps, we brought along part of the write-mode, but none of the testing. For now, removing write mode from the standalone app, since file mode does not figure into our testing.
> Remove file write mode from test app

- common/changes/@itwin/appui-layout-react/tool-settings-fix_2023-08-14-12-55.json
- ui/appui-layout-react/src/appui-layout-react/state/TabState.ts
- ui/appui-layout-react/src/test/state/TabState.test.ts
- ui/appui-layout-react/src/test/state/ToolSettingsState.test.ts
This PR fixes an issue where tool settings would get removed while removing one of the widgets.
Added additional unit tests. We can add additional e2e tests after #436
> Fix an issue with unintentionally removing tool settings

- common/api/appui-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/raplemie-pushbackToolbarDeprecation_2023-08-14-14-21.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/toolbar/ToolbarWithOverflow.tsx
Removed deprecation tag on `ToolbarWithOverflow` component, (we should add it back when we have the proper codemod available, until then, both component do the same thing and will not cause issues to the users anyway.
Removed line in NextVersion as the component is no longer deprecated.
N/A
> Push back deprecation for codemod availability

- common/api/components-react.api.md
- common/api/summary/components-react.exports.csv
- common/changes/@itwin/components-react/filter_builder_ability_to_ignore_errors_2023-08-29-11-48.json
- docs/changehistory/NextVersion.md
- ui/components-react/src/components-react/filter-builder/FilterBuilderContext.tsx
- ui/components-react/src/components-react/filter-builder/FilterBuilderState.ts
- ui/components-react/src/test/filter-builder/FilterBuilderState.test.ts
Add ability to get filter without persisting encountered errors in a state. This is useful if component want to do some actions with filter but does not want to show errors in UI.
Prerequisite for https://github.com/iTwin/presentation/issues/221
> Filter builder: Ability to build filter ignoring errors

- common/changes/@itwin/components-react/raplemie-defaultTypeconverterRequire_2023-08-30-17-21.json
- docs/changehistory/NextVersion.md
- ui/components-react/src/components-react/converters/StringTypeConverter.ts
- ui/components-react/src/components-react/converters/TypeConverterManager.ts
Removed `require` call in `TypeConverterManager` and moved `StringTypeConverter` registration within that file as this is the default converter, it is expected to always be registered. (Instead of doing the lazy initialization we had in 3.x that could cause an issue if StringTypeConverter was never registered.
Built applications and ran tests.
fixes #465
> Remove `require` call in `TypeConverterManager`

- common/changes/@itwin/appui-react/issue-480_2023-09-08-08-04.json
- docs/changehistory/NextVersion.md
- full-stack-tests/ui/tests/widget-state.test.ts
- ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
- ui/appui-react/src/appui-react/frontstage/InternalFrontstageManager.ts
- ui/appui-react/src/test/frontstage/FrontstageDef.test.tsx
This PR fixes #480 by correctly returning an updated `WidgetDef` instance in `useSpecificWidgetDef`.
Additional unit test is added.
> Fix `useSpecificWidgetDef` to correctly return re-created `WidgetDef`

- common/changes/@itwin/appui-layout-react/issue-456_2023-09-13-08-59.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/variants/core-3x/pnpm-lock.yaml
- docs/changehistory/NextVersion.md
- ui/appui-layout-react/package.json
- ui/appui-layout-react/src/appui-layout-react/base/LayoutStore.tsx
This PR fixes #456 by replacing `useStore` with `useStoreWithEqualityFn` to fix the deprecation warning.
Tested by updating `zustand` (deprecation is in 4.4.0) and launching the test-app.
> Fix `zustand` deprecation warning

- common/api/appui-react.api.md
- common/changes/@itwin/appui-layout-react/floating-widget-options_2023-09-18-07-47.json
- common/changes/@itwin/appui-react/floating-widget-options_2023-09-18-07-47.json
- docs/changehistory/NextVersion.md
- docs/storybook/package.json
- docs/storybook/src/AppUiDecorator.tsx
- docs/storybook/src/components/ContextMenu.stories.tsx
- docs/storybook/src/components/ToolbarComposer.stories.tsx
- docs/storybook/src/components/TreeWidget.stories.tsx
- docs/storybook/src/hooks/useIsBackstageOpen.stories.tsx
- docs/storybook/src/widget/CanFloatOptions.stories.tsx
- docs/storybook/src/widget/CanFloatOptions.tsx
- ui/appui-layout-react/src/appui-layout-react/widget/FloatingWidget.scss
- ui/appui-layout-react/src/appui-layout-react/widget/TabBar.scss
- ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
- ui/appui-react/src/appui-react/widgets/Widget.tsx
This PR adds a story to showcase different [CanFloatWidgetOptions ](https://www.itwinjs.org/reference/appui-react/widget/canfloatwidgetoptions).
This PR also disables user selection when dragging a widget tab to avoid unintentional selection.
Documentation of related APIs is updated.
N/A
> Add storybook for floating widget options

- common/config/rush/pnpm-lock.yaml
- common/config/rush/variants/core-3x/pnpm-lock.yaml
- docs/storybook/package.json
- docs/storybook/src/widget/CanPopout.stories.tsx
- docs/storybook/src/widget/EmptyState.stories.tsx
- docs/storybook/src/widget/EmptyState.tsx
Add stories to showcase different strategies to display the empty state of a widget.
N/A
> Add empty state stories

- test-apps/appui-test-app/standalone/src/frontend/appui/frontstages/example-stages/CustomFrontstage.tsx
- test-apps/appui-test-app/standalone/src/frontend/appui/frontstages/example-stages/ViewportFrontstage.tsx
Remove code snippets previously used for the same code block to avoid deprecated APIs in the docs.
N/A
> Use single code snippet for docs

- common/config/azure-pipelines/jobs/docs-ci.yaml
Ability to manually tag the docs w/o creating a new release.
Ran the docs pipeline to verify.
> Add `tagDocs` parameter to `docs` pipeline

- common/changes/@itwin/components-react/hooks_fix_2023-10-20-12-48.json
- common/changes/@itwin/core-react/hooks_fix_2023-10-20-12-48.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/variants/core-3x/pnpm-lock.yaml
- docs/changehistory/NextVersion.md
- ui/components-react/package.json
- ui/components-react/src/components-react/common/UseAsyncValue.tsx
- ui/components-react/src/components-react/common/UseDebouncedAsyncValue.ts
- ui/components-react/src/test/common/UseDebouncedAsyncValue.test.tsx
- ui/core-react/src/core-react/utils/hooks/useDisposable.ts
Fixed `useAsyncValue` hook not working in React 18 strict mode because `useEffect` was not symmetrical.
Fixed `useDisposable` hook not working in React 18 strict mode because `useEffect` was not symmetrical.
Cleaned up `useDebouncedAsyncValue` hook.
Bumped `react-window` and `react-highlight-words` versions to the ones that has React 18 as peerDependency.
Manual testing in viewer app running with React 18 in strict mode.
> Fix custom hooks not working in React 18 strict mode

- common/changes/@itwin/appui-react/fix-onWidgetStateChanged_2023-10-24-09-22.json
- ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
This PR fixes an issue where a Hidden widget state changed event is emitted when dragging a widget tab.
Tested via the test app.
> Do not emit Hidden widget state changed event when dragging a widget

- common/changes/@itwin/appui-react/raplemie-ViewportExcessiveChangeViews_2023-10-27-20-34.json
- common/changes/@itwin/imodel-components-react/raplemie-ViewportExcessiveChangeViews_2023-10-27-20-34.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/content/FloatingViewportContent.tsx
- ui/imodel-components-react/src/imodel-components-react/viewport/ViewportComponent.tsx
- `ViewportComponent`: Remove the default evaluation of the `viewState` in the `useState` initialiser because it gets automatically reset to `undefined` afterwards, but was causing a creation of the viewport (fulfilling the `viewportRef` then reassigned the `viewState` value that had just been recalculated. Since we want to reset the view when a new viewState is provided, we can't remove the "set...(undefined)", so simply starting with undefined resolves this issue.
- `FloatingViewportContent`: The `changeView` call is not necessary because a new `viewstate` cause the viewportControl to be rememoized, which handles the viewstate change itself. However having it was causing any changes to the viewport (for example in the ref call) to be ignored/reset.
Tested manually in many scenario, …
> Fix unneeded `changeView` call being done on mount

- common/api/appui-layout-react.api.md
- common/api/appui-react.api.md
- common/api/summary/appui-layout-react.exports.csv
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-layout-react/raplemie-previewMaximizeFloating_2023-11-09-19-21.json
- common/changes/@itwin/appui-react/raplemie-previewMaximizeFloating_2023-11-09-19-21.json
- docs/changehistory/NextVersion.md
- test-apps/appui-test-app/appui-test-providers/src/ui/providers/PreviewFeaturesToggleProvider.tsx
- ui/appui-layout-react/src/appui-layout-react/preview/PreviewFeatures.tsx
- ui/appui-layout-react/src/appui-layout-react/widget/Buttons.tsx
- ui/appui-layout-react/src/appui-layout-react/widget/FloatingWidget.scss
- ui/appui-layout-react/src/appui-layout-react/widget/FloatingWidget.tsx
- ui/appui-layout-react/src/appui-layout-react/widget/PreviewMaximizeToggle.tsx
- ui/appui-layout-react/src/appui-layout-react/widget/Tab.tsx
- ui/appui-layout-react/src/appui-layout-react/widget/TabBar.scss
- ui/appui-layout-react/src/test/preview/PreviewFeatures.test.tsx
- ui/appui-react/src/appui-react.ts
- ui/appui-react/src/appui-react/configurableui/state.ts
- ui/appui-react/src/appui-react/preview/PreviewFeatures.ts
* Added new preview feature to allow floating widgets to have a maximize button, once clicked, the widget will take all the visible space of the ConfigurableUI, SendBack is disabled in this state, however "Popout" is still available.
* Added a `previewState` and `previewDispatch` to the appui-layout-react `usePreviewFeatures` so it is now possible to save state for a preview feature without having to change the existing code (NinezoneState actually get saved to localstorage, so I did not want the preview feature to be saved there, that's the main reason, the second is to centralize so we dont have to create a new context for each new feature)
* Removed "PreviewFeatures" type from the redux actions and replaced with a more general one because of the way the type was being computed, the …
> New `enableMaximizedFloatingWidget` preview feature

- common/changes/@itwin/appui-react/raplemie-widgetToolSettingsRefresh_2023-11-10-21-44.json
- docs/changehistory/NextVersion.md
- full-stack-tests/ui/tests/tool-settings.test.ts
- test-apps/appui-test-app/appui-test-providers/src/tools/SampleTool.ts
- ui/appui-react/src/appui-react/widget-panels/ToolSettings.tsx
When mounting toolSettings in Docked or Widget form, will refresh the settings from the tool.
Added same forceRefresh fix on node changes to Widget form than always existed in Docked form
Validated cover and e2e.
Added relevant e2e test to validate that tool settings gets correctly updating when changing docked/widget.
Resolves #378
> Missing refresh of tool setting source on mount

- common/changes/@itwin/appui-react/raplemie-lostFrontstageChanges_2023-11-17-18-58.json
- docs/changehistory/NextVersion.md
- test-apps/appui-test-app/appui-test-providers/src/ui/providers/PreviewFeaturesToggleProvider.tsx
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
* Added a way to force debounced setting save to not be lost when closing a frontstage.
* ~Also fixed a logic issue in the PreviewFeatureToggle in test app.~ (Removed to facilitage backport, unrelated)
Manual tests using #515 scenario, validated local storage consistent updates.
Fixes #515
> Save pending debounced settings on close

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/preview-features-out-of-redux_2023-11-24-11-00.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/variants/core-3x/pnpm-lock.yaml
- docs/storybook/src/components/ToolbarComposer.stories.tsx
- ui/appui-react/package.json
- ui/appui-react/src/appui-react.ts
- ui/appui-react/src/appui-react/UiFramework.ts
- ui/appui-react/src/appui-react/configurableui/state.ts
- ui/appui-react/src/appui-react/content/IModelViewport.tsx
- ui/appui-react/src/appui-react/preview/PreviewFeatures.ts
- ui/appui-react/src/appui-react/toolbar/Toolbar.tsx
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
- ui/appui-react/src/test/UiFramework.test.ts
- ui/appui-react/src/test/redux/StateManager.test.ts
- ui/appui-react/src/test/setup.test.ts
Remove `previewFeatures` from the redux store to avoid having a requirement of a Provider.
Added a hidden `newToolbars` preview feature which can be enabled in `ToolbarComposer` story.
> Remove preview features from redux store

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/raplemie-unneededComplexity_2023-11-29-17-16.json
- ui/appui-react/src/appui-react/UiFramework.ts
Removed `initializeEx` internal function from `UiFramework`. This method was created back when UiFramework was managing different services (IModelServices, ProjectServices, LoginServices...) to enable providing mocks of those services in tests. The services are long gone and there really is no need to have the internal version which had been a 1:1 match for years now...
N/A (`initializeEx` is internal and not called anywhere except in the method above it)
> Remove unneeded UiFramework complexity

- common/changes/@itwin/appui-react/raplemie-0x0ViewportHandling_2023-12-04-21-46.json
- common/changes/@itwin/imodel-components-react/raplemie-0x0ViewportHandling_2023-12-04-21-46.json
- ui/appui-react/src/appui-react/content/InternalContentViewManager.ts
- ui/imodel-components-react/src/imodel-components-react/viewport/ViewportComponent.tsx
- ui/imodel-components-react/src/test/viewport/ViewportComponent.test.tsx
Include a `ResizeObserver` to validate that the `div` targeted for iTwin.js `viewport` actually have non 0 height and width (otherwise it crashes anyway and the fix was needed by user devs)
`viewportRef` will not be set until the `div` is large enough, and resize observer is completely removed after initial render, to have same result as before.
Updated tests to have a size, and added a tests for 0x0 sizes.
Resolves #608
> Delay viewport creation to non 0x0 div.

- common/changes/@itwin/components-react/filterer-edit-filtering-constructors_2023-12-07-13-35.json
- docs/changehistory/NextVersion.md
- ui/components-react/src/components-react/propertygrid/dataproviders/filterers/DisplayValuePropertyDataFilterer.ts
- ui/components-react/src/components-react/propertygrid/dataproviders/filterers/LabelPropertyDataFilterer.ts
- ui/components-react/src/components-react/propertygrid/dataproviders/filterers/PropertyCategoryLabelFilterer.ts
- ui/components-react/src/test/propertygrid/dataproviders/filterers/DisplayValuePropertyDataFilterer.test.ts
- ui/components-react/src/test/propertygrid/dataproviders/filterers/LabelPropertyDataFilterer.test.ts
- ui/components-react/src/test/propertygrid/dataproviders/filterers/PropertyCategoryLabelFilterer.test.ts
Change the constructor implementation of data filterers to automatically convert filterText to lowercase, as it prevents bugs from happening if user would forget to manually set the filterer text after constructing.
Tested all filterers with a case where filterText isn't set with the setter, but rather with the constructor.
> Fix constructors of data filterers

- common/changes/@itwin/appui-react/raplemie-restoreLayout_2023-12-12-20-31.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
- ui/appui-react/src/appui-react/preview/PreviewFeatures.tsx
- ui/appui-react/src/appui-react/widgets/WidgetDef.tsx
* Adding "pinned" state restore to panels
* `setWidgetState` will now explicitly skip calls for `isStatusBar` since this is not handled and caused a crash with recent changes to handle "Unloaded" state.
* Updated NextVersion.md to follow new suggested structure.
Validated that calling the "Restore Layout" tool no longer caused a crash, and reset the "pinned" state.
Fixes #254
> Fix RestoreLayout tool

- common/changes/@itwin/components-react/property-grid-fix-default-orientation_2023-12-18-10-51.json
- docs/changehistory/NextVersion.md
- ui/components-react/src/components-react/propertygrid/component/VirtualizedPropertyGrid.tsx
- ui/components-react/src/test/propertygrid/component/VirtualizedPropertyGridWithDataProvider.test.tsx
There was an issue with orientation of `PropertyGrid` items being set incorrectly when it is first shown. ([See issue](https://github.com/orgs/iTwin/projects/20/views/19?pane=issue&itemId=47330041))
This was fixed by not waiting for a component to be updated to find out what is the correct orientation for the item and instead, determine the correct orientation in the constructor.
Added a test case to ensure that when orientation is undefined - appropriate one is assigned.
> Fix logic of default orientation of PropertyGrid elements.

- full-stack-tests/ui/tests/Utils.ts
- full-stack-tests/ui/tests/popout-widget.test.ts
- full-stack-tests/ui/tests/widget-state.test.ts
Minor fixes on tests.
Spent hours trying to figure what's going on, seems that the more you run these tests, either in VSCode or in playwright ui `npm test -- --ui`, at some point everything get so slow that the tests may take up to a minute to run (and we bail out at 30 seconds, and 5 seconds for each excepts)
Not sure what to do next, seems a bit less flacky now, at least for these specific tests.
Trace show that at some point it takes up to 20 seconds before the page open in the browser window, in which case the tests no longer have enough time to run... Confusion all over the place :(
A Lot, tried a bunch of things, thought I had improvement, then end up in a stray of failures...
> Improve e2e tests

- common/changes/@itwin/appui-layout-react/fix-panel-resize_2024-01-10-17-56.json
- full-stack-tests/ui/tests/stage-panel.test.ts
- ui/appui-layout-react/src/appui-layout-react/widget-panels/Grip.tsx
This PR fixes an issue that caused the panel to become unresizable due to a [transient update](https://github.com/pmndrs/zustand?tab=readme-ov-file#transient-updates-for-often-occurring-state-changes) handler added after the [PANEL_INITIALIZE](https://github.com/iTwin/appui/blob/e3e44fd0c8f276fefecc30baa0f454438eb6429b/ui/appui-layout-react/src/appui-layout-react/widget-panels/useAnimatePanel.tsx#L108) action was dispatched.
Tested via standalone test-app with a single right panel in a frontstage.
> Fix panel resize issue

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/fix-panel-init_2024-01-11-12-59.json
- full-stack-tests/ui/tests/Utils.ts
- full-stack-tests/ui/tests/floating-widget.test.ts
- full-stack-tests/ui/tests/stage-panel.test.ts
- full-stack-tests/ui/tests/widget-state.test.ts
- test-apps/appui-test-app/appui-test-providers/src/appui-test-providers.ts
- test-apps/appui-test-app/appui-test-providers/src/ui/frontstages/TestFrontstageProvider.tsx
- test-apps/appui-test-app/standalone/src/frontend/index.tsx
- ui/appui-react/src/appui-react.ts
- ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
- ui/appui-react/src/appui-react/frontstage/StandardFrontstageProvider.tsx
- ui/appui-react/src/appui-react/stagepanels/StagePanelConfig.ts
- ui/appui-react/src/appui-react/stagepanels/StagePanelDef.tsx
- ui/appui-react/src/appui-react/stagepanels/StagePanelState.tsx
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
Add additional e2e tests and fix panel initialization quirks introduced with https://github.com/iTwin/appui/pull/636
Added additional e2e tests
> Fix panel initialization

- docs/storybook/src/frontstage/SplitViewport.stories.tsx
- docs/storybook/src/frontstage/SplitViewport.tsx
- test-apps/appui-test-app/appui-test-providers/src/ui/providers/MessageUiItemsProvider.tsx
- Added a split viewport story to the storybook. The tools in toolbars change based on which view is active
- Check out the storybook
> Add story for split viewport

- common/config/rush/pnpm-lock.yaml
- common/config/rush/variants/core-3x/pnpm-lock.yaml
- docs/storybook/.storybook/addons/DemoIModel.tsx
- docs/storybook/package.json
- docs/storybook/src/AppUiStory.tsx
- docs/storybook/src/frontstage/ToolSettings.tsx
- docs/storybook/src/openDemoIModel.ts
- test-apps/appui-test-app/appui-test-providers/package.json
- test-apps/appui-test-app/appui-test-providers/src/appui-test-providers.ts
- test-apps/appui-test-app/appui-test-providers/src/createBlankConnection.ts
- test-apps/appui-test-app/appui-test-providers/src/ui/providers/ComponentExamplesProvider.tsx
- test-apps/appui-test-app/standalone/src/frontend/appui/BlankConnection.ts
Add the capability to open a blank iModel connection from storybook. It is needed since opening a checkpoint is slower and requires a network connection, while iModel connection is required for some stories.
Ran storybook to verify
> Add capability to open a blank iModel connection from storybook

- common/changes/@itwin/components-react/fix_tree_multi_select_on_ipad_2024-02-15-12-44.json
- docs/changehistory/NextVersion.md
- ui/components-react/src/components-react/tree/controlled/internal/TreeSelectionManager.ts
- ui/components-react/src/test/tree/controlled/internal/TreeSelectionManager.test.ts
Treat `Cmd` key on Apple devices as `Ctrl` when clicking on tree nodes. `Ctrl` + mouse click on Apple devices acts as right mouse button click.
Fixes: https://github.com/iTwin/viewer-components-react/issues/770
Tested manually.
> `ControlledTree`: add ability to select multiple nodes using `CMD` key + mouse click

- common/config/rush/pnpm-config.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/variants/core-3x/common-versions.json
- common/config/rush/variants/core-3x/pnpm-lock.yaml
- common/config/rush/variants/core-3x/repo-state.json
- common/scripts/install-run.js
- rush.json
This PR bumps an `ip` version to fix the audit error.
Rush variants seem to no longer work correctly after the latest rush version update #732 - downgraded it back for now.
N/A
> Bump `ip` version

- common/changes/@itwin/appui-react/test-accudraw_2024-02-29-15-27.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/variants/core-3x/pnpm-lock.yaml
- test-apps/appui-test-app/standalone/README.md
- test-apps/appui-test-app/standalone/package.json
- test-apps/appui-test-app/standalone/src/common/TestAppConfiguration.ts
- test-apps/appui-test-app/standalone/src/frontend/appui/LocalFileSupport.ts
- test-apps/appui-test-app/standalone/src/frontend/appui/frontstages/EditorFrontstageProvider.tsx
- test-apps/appui-test-app/standalone/src/frontend/appui/useEditorToolSettings.tsx
- test-apps/appui-test-app/standalone/src/frontend/index.tsx
- ui/appui-react/src/appui-react/accudraw/AccuDrawFieldContainer.tsx
- ui/appui-react/src/appui-react/accudraw/AccuDrawInputField.tsx
Add a frontstage to test AccuDraw to the standalone test-app. iTwin/itwinjs-core#6478
Maintenance: cleaned up AccuDraw event listeners.
Tested manually in a standalone test-app.
> Add a frontstage to test AccuDraw

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/deprecate-non-snap-toolbar-opacity-setting_2024-03-12-12-56.json
- common/changes/@itwin/components-react/deprecate-non-snap-toolbar-opacity-setting_2024-03-12-12-56.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/framework/FrameworkVisibility.ts
- ui/appui-react/src/appui-react/settings/ui/UiSettingsPage.tsx
- ui/appui-react/src/appui-react/toolbar/Toolbar.tsx
- ui/appui-react/src/appui-react/toolbar/ToolbarComposer.tsx
- ui/appui-react/src/appui-react/widgets/BackstageAppButton.tsx
- ui/appui-react/src/appui-react/widgets/NavigationWidgetComposer.tsx
- ui/components-react/src/components-react/toolbar/InternalToolbarComponent.tsx
Deprecated `FrameworkVisibility.useProximityOpacity`. Modified some toolbar components so `FrameworkVisibility.snapyWidghetOpacity` is now independent from `useProximityOpacity` (before the snap opacity would not work without the turning on the proximity opacity setting).
Tested in standalone test-app.
> Deprecate non-snap toolbar opacity setting

- common/api/appui-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/fix-757_2024-03-15-09-09.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
- ui/appui-react/src/appui-react/widgets/WidgetDef.tsx
- ui/appui-react/src/test/frontstage/FrontstageDef.test.tsx
- ui/appui-react/src/test/widgets/WidgetDef.test.tsx
Fixes #757 
`UiFramework.frontstages.onWidgetStateChangedEvent` event will now correctly emit widget state changes.
Values emitted by the event will match `WidgetState` returned by `WidgetDef.state`.
Added additional unit tests.
Tested via standalone test-app:
- Open <http://localhost:3000/?frontstage=appui-test-providers:WidgetApi>
- Open `Layout Info` widget
- Select a widget to inspect i.e. `FW-1`
- Interact with `FW-1` widget, note how `state={WidgetState}` output changes
> Fix `UiFramework.frontstages.onWidgetStateChangedEvent` event to correctly emit widget state changes

- common/changes/@itwin/appui-react/fix-770_2024-03-19-12-51.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/theme/ThemeManager.tsx
Fixes #770 by correctly handling `os` theme in `ThemeManager` for backwards compatibility.
N/A
> Fix `ThemeManager` to correctly handle `os` theme

- common/changes/@itwin/imodel-components-react/nam-listener-fix_2024-03-19-15-13.json
- docs/changehistory/NextVersion.md
- ui/imodel-components-react/src/imodel-components-react/viewport/ViewportComponent.tsx
Link to issue in backlog: https://github.com/iTwin/itwinjs-backlog/issues/1065
As part of a memory leak investigation, I'm looking at places that may have references (pointers) to viewports and whether those places have been properly disposed. One case is with event listeners and javascript closures. The handleWindowUnload() event listener is a closure, that has a reference to a screenViewport object. If the event listener is never removed, the javascript garbage collector can't dispose of variables that event listener / closure uses, including the parent object of the event listener. This leads to a memory leak, because we can't dispose of any references that the ViewportComponent uses (like the screenViewportRef as an example)
Attached is an example of a memory snapshot on chrome …
> Fix event listener disposal to address viewport memory leak.

- common/api/appui-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/panel-stage-percentage-size_2024-03-26-12-36.json
- docs/changehistory/NextVersion.md
- test-apps/appui-test-app/appui-test-providers/src/ui/frontstages/TestFrontstageProvider.tsx
- test-apps/appui-test-app/appui-test-providers/src/ui/widgets/LayoutWidget.tsx
- ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
- ui/appui-react/src/appui-react/frontstage/StandardFrontstageProvider.tsx
- ui/appui-react/src/appui-react/layout/state/NineZoneAction.ts
- ui/appui-react/src/appui-react/layout/state/NineZoneStateReducer.ts
- ui/appui-react/src/appui-react/layout/state/PanelState.ts
- ui/appui-react/src/appui-react/layout/state/internal/PanelStateHelpers.ts
- ui/appui-react/src/appui-react/stagepanels/StagePanelConfig.ts
- ui/appui-react/src/appui-react/stagepanels/StagePanelDef.tsx
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
- ui/appui-react/src/test/frontstage/FrontstageDef.test.tsx
- ui/appui-react/src/test/layout/state/internal/PanelStateHelpers.test.ts
- ui/appui-react/src/test/stagepanels/StagePanelDef.test.tsx
Added ability to set `StagePanel` size as percentage value. This involves deprecating old `size` and `minSize` getters/setters and introducing new `sizeSpec` and `minSizeSpec` getters/setters. The same was done for `StagePanelConfig` as well.
Tested in standalone test-app. Tried with old `size`, `minSize` and `maxSize` properties, then with new properties, various combinations etc.
> Panel stage percentage size

- common/changes/@itwin/components-react/like-operator-note_2024-04-02-07-32.json
- ui/components-react/src/components-react/filter-builder/Operators.ts
Added note to `PropertyFilterRuleOperator` that like operator should be handled as a contains operator as discussed in [496](https://github.com/iTwin/presentation/pull/496).
No testing required.
> Add note to PropertyFilterRuleOperator

- common/changes/@itwin/appui-react/fix-tool-settings-overlay_2024-04-04-14-47.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/layout/StandardLayout.scss
This PR fixes an issue where tool settings and status bar would overlay the content (i.e. viewport).
This would cause certain negative side effects like content view-overlay hiding below tool settings or imodeljs-icon hiding below status bar.
| Before  | After |
| ------------- | ------------- |
| ![Screenshot 2024-04-04 at 17 56 18](https://github.com/iTwin/appui/assets/10091419/3a4e9783-330a-48ca-93ae-321bcd4312da) | ![Screenshot 2024-04-04 at 17 56 38](https://github.com/iTwin/appui/assets/10091419/9fa218d2-669f-4609-94eb-3897aeb4f4a8) |
This unintentional behavior was first introduced with #736 (released in [4.10.0](https://github.com/iTwin/appui/releases/tag/release%2F4.10.0)).
Tested via standalone test-app.
> Fix standard layout to prevent content overlays

- common/changes/@itwin/appui-react/bdp-docs-remove-frontstage-links_2024-04-05-15-02.json
- common/changes/@itwin/components-react/bdp-docs-remove-frontstage-links_2024-04-05-15-02.json
- common/changes/@itwin/core-react/bdp-docs-remove-frontstage-links_2024-04-05-15-02.json
- common/changes/@itwin/imodel-components-react/bdp-docs-remove-frontstage-links_2024-04-05-15-02.json
- ui/appui-react/src/appui-react/framework/FrameworkFrontstages.ts
- ui/appui-react/src/appui-react/frontstage/InternalFrontstageManager.ts
- ui/appui-react/src/appui-react/widgets/StatusBarWidgetComposerControl.tsx
These are invalid links due to the `Frontstage` class being removed, but just now being flagged as invalid after some pending upgrades and fixes to the docs link resolution. 
FYI, the docs link resolution is very convoluted and almost certainly contains more bugs. It will be replaced in the next quarter or so.
> docs: remove frontstage links

- common/changes/@itwin/appui-react/fix-778_2024-04-29-10-56.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/frontstage/InternalFrontstageManager.ts
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
- ui/appui-react/src/test/frontstage/FrontstageDef.test.tsx
Fixes #778 by correctly updating widgets if a new provider is registered while a frontstage is activating.
Added a unit test.
> Fix `FrontstageDef` to correctly update widgets while activating

- common/changes/@itwin/core-react/disable-button-propagation_2024-04-29-12-44.json
- docs/changehistory/NextVersion.md
- ui/core-react/src/core-react/tree/ExpansionToggle.tsx
Disabled `onMouseDown` propagation for `ExpansionToggle` as it was unnecessarily raising selection modification events.
Manual testing in test app.
> Disable onMouseDown propagation for `ExpansionToggle`

- common/changes/@itwin/components-react/drag-selection-improvement_2024-04-30-12-28.json
- docs/changehistory/NextVersion.md
- ui/components-react/src/components-react/tree/controlled/internal/TreeSelectionManager.ts
- ui/components-react/src/test/tree/controlled/TreeEventDispatcher.test.ts
Updated `TreeSelectionManager` to only start a drag operation when a second node is selected to avoid multiple `selectionModified` events being raised.
Manual testing in test-app.
> Do not start drag operation when only initial node is selected

- common/api/components-react.api.md
- common/api/summary/components-react.exports.csv
- common/changes/@itwin/components-react/deprecate_renderers_2024-05-07-11-19.json
- common/config/rush/pnpm-lock.yaml
- docs/changehistory/NextVersion.md
- ui/components-react/package.json
- ui/components-react/src/components-react/properties/ValueRendererManager.tsx
- ui/components-react/src/components-react/properties/renderers/value/DoublePropertyValueRenderer.tsx
- ui/components-react/src/components-react/properties/renderers/value/NavigationPropertyValueRenderer.tsx
- ui/components-react/src/components-react/propertygrid/internal/flat-items/MutableFlatGridItem.ts
- ui/components-react/src/test/properties/renderers/value/DoublePropertyValueRenderer.test.tsx
- ui/components-react/src/test/properties/renderers/value/NavigationPropertyValueRenderer.test.tsx
- ui/components-react/src/test/propertygrid/component/internal/flat-items/FlatGridTestUtils.ts
Deprecated property value renderers that are no longer used. Follow up to https://github.com/iTwin/appui/pull/831
Additionally removed deprecated `shortid` dependency.
> Deprecate unused property value renderers

- common/changes/@itwin/appui-react/fix-docked-bar-position_2024-05-08-04-51.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/widget-panels/DockedBar.scss
When `contentAlwaysMaxSize` preview feature is enabled, the content takes up the whole window. In [this PR](https://github.com/iTwin/appui/pull/821) I removed `position: absolute` from status bar and tool settings but they are needed in this situation so the bars can be displayed above the content.
Tested in test-app.
> Change DockedBar position to relative

- common/api/appui-react.api.md
- common/changes/@itwin/appui-codemod/ts53-itwin-build-tools_2024-05-07-18-39.json
- common/changes/@itwin/appui-react/ts53-itwin-build-tools_2024-05-07-18-39.json
- common/changes/@itwin/components-react/ts53-itwin-build-tools_2024-05-07-18-39.json
- common/changes/@itwin/core-react/ts53-itwin-build-tools_2024-05-07-18-39.json
- common/changes/@itwin/imodel-components-react/ts53-itwin-build-tools_2024-05-07-18-39.json
- common/config/rush/common-versions.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- docs/storybook/package.json
- test-apps/appui-test-app/appui-test-providers/package.json
- test-apps/appui-test-app/connected/package.json
- test-apps/appui-test-app/standalone/package.json
- tools/codemod/package.json
- ui/appui-react/package.json
- ui/components-react/package.json
- ui/core-react/package.json
- ui/imodel-components-react/package.json
Consume latest [@itwin/build-tools](https://github.com/iTwin/itwinjs-core/tree/master/tools/build) to produce documentation with newer TypeDoc schema. As a consequence, upgrade TypeScript to v5.3.3.
> ts5.3.3; update @itwin/build-tools to update doc generation

- docs/storybook/src/components/PropertyGrid.stories.tsx
Add the required `width` property to the property grid storybook to fix column resizing.
N/A
> Add required width property to fix column resizing in storybook.

- common/changes/@itwin/components-react/jon-fix-property-grid-text-selection_2024-05-23-06-54.json
- common/changes/@itwin/core-react/jon-fix-property-grid-text-selection_2024-05-23-06-54.json
- docs/changehistory/NextVersion.md
- docs/storybook/src/components/PropertyGrid.stories.tsx
- ui/components-react/src/components-react/properties/renderers/PropertyGridColumns.ts
- ui/components-react/src/components-react/properties/renderers/PropertyView.tsx
- ui/components-react/src/components-react/properties/renderers/label/PropertyLabelRenderer.scss
- ui/components-react/src/components-react/properties/renderers/label/PropertyLabelRenderer.tsx
- ui/components-react/src/components-react/propertygrid/component/PropertyGridEventsRelatedPropsSupplier.tsx
- ui/components-react/src/components-react/propertygrid/component/VirtualizedPropertyGrid.scss
- ui/components-react/src/test/properties/renderers/PropertyView.test.tsx
- ui/components-react/src/test/propertygrid/component/ColumnResizingPropertyListPropsSupplier.test.tsx
- ui/core-react/src/core-react/elementseparator/ElementSeparator.scss
- ui/core-react/src/core-react/elementseparator/ElementSeparator.tsx
- Moved `user-select: none` from property grid to element separator to allow a user to highlight the text values.
- Add `tabindex: -1` to element separator so it is not keyboard focusable. It already had `:focus { outline: 0; }` which hides the focus, this now disables focus.
- Changed `.components-property-label-renderer-colon` from a `<span>` to an `::after`.
- Confirmed that resizing columns does not unintentionally highlight text.
- Used the <kbd>tab</kbd> to confirm that the resizer is no longer taking focus.
> Fix property grid text selection

- docs/storybook/src/AppUiStory.tsx
- docs/storybook/src/frontstage/notifications/OutputMessage.stories.tsx
- docs/storybook/src/frontstage/notifications/OutputMessage.tsx
- docs/storybook/src/frontstage/notifications/OutputPrompt.stories.tsx
- docs/storybook/src/frontstage/notifications/OutputPrompt.tsx
This PR adds storybook stories to demonstrate `AppNotificationManager` APIs.
A couple of issues were identified:
- `updatePointerMessage` requires a `relativePosition` parameter (that is optional in base class).
- `Alert` message type produces a dialog that is poorly styled
- `outputPrompt` timing issues (API must be called after the tool assistance field is mounted)
N/A
> Add notification stories

- common/changes/@itwin/components-react/issue-857_2024-06-03-16-26.json
- docs/changehistory/NextVersion.md
- docs/storybook/src/components/PropertyGrid.stories.tsx
- ui/components-react/src/components-react/properties/renderers/value/UrlPropertyValueRenderer.tsx
- ui/components-react/src/components-react/propertygrid/component/PropertyGridCommons.ts
- ui/components-react/src/test/properties/renderers/value/UrlPropertyValueRenderer.test.tsx
- ui/components-react/src/test/propertygrid/component/internal/PropertyGridCommons.test.ts
This PR fixes #857 by updating handlers of `VirtualizedPropertyGrid` and `UrlPropertyValueRenderer` components to open links with `pw` scheme in a new window.
Updated unit tests and added story.
> Open 'pw' scheme links in a new window

- common/changes/@itwin/appui-react/issue-867_2024-06-11-11-51.json
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
This PR fixes #867 by correctly reopening popout widgets when switching to the initialized frontstage in an electron app.
Tested manually in a standalone test app.
> Re-open popout widgets in electron app

- common/api/core-react.api.md
- common/api/summary/components-react.exports.csv
- common/changes/@itwin/components-react/editor-popup_2024-06-14-11-20.json
- common/changes/@itwin/core-react/editor-popup_2024-06-14-11-20.json
- docs/changehistory/NextVersion.md
- ui/components-react/src/components-react/editors/PopupButton.tsx
- ui/core-react/src/core-react/popup/Popup.tsx
Container used to portal components had higher z-index than `Popup` components. Changed editors to use same portal container. Required to fix https://github.com/iTwin/viewer-components-react/issues/921.
Tested manually
> Portal editor to same container used to portal other components

- common/changes/@itwin/appui-react/fix-886_2024-06-26-15-22.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/childwindow/InternalChildWindowManager.scss
- ui/appui-react/src/appui-react/childwindow/InternalChildWindowManager.tsx
- ui/appui-react/src/appui-react/preview/reparent-popout-widgets/PopoutThemeProvider.tsx
This PR fixes #886 by portalling popovers to a container with fixed position.
Tested via standalone test app. `Layout Info` widget can be used to reproduce this issue.
> Fix unintentional popout widget transition

- common/changes/@itwin/components-react/master_2024-07-02-06-46.json
- ui/components-react/src/components-react/propertygrid/internal/flat-items/MutableCategorizedArrayProperty.ts
- ui/components-react/src/test/propertygrid/component/internal/flat-items/CategorizedArrayProperty.test.ts
- ui/components-react/src/test/propertygrid/component/internal/flat-items/FlatGridTestUtils.ts
Part of https://github.com/iTwin/presentation/issues/654
Property record description (if present) will be shown next to the index for array property items.
This should improve user experience when browsing through the property grid having many related instances.
A unit test was added.
> Show property record description next to array indices

- common/changes/@itwin/components-react/master_2024-07-04-14-20.json
- common/config/rush/pnpm-lock.yaml
- docs/changehistory/NextVersion.md
- ui/components-react/package.json
- ui/components-react/src/components-react/common/HighlightedText.tsx
- ui/components-react/src/test/common/HighlightedText.test.tsx
Fixes https://github.com/iTwin/itwinjs-core/issues/3776. Due to a bug in `react-highlight-words`, `activeMatchIndex` does not correctly work when there are adjacent highlights. The issue was reported and has not been fixed in years so I am switching to using a custom implementation for text highlighting as it is fairly simple.
Added additional unit tests and manually tested in a test app.
> Fix active match index not working with adjacent text highlights

- common/api/core-react.api.md
- common/changes/@itwin/appui-react/issue-900_2024-07-09-07-50.json
- common/changes/@itwin/components-react/issue-900_2024-07-09-07-50.json
- common/changes/@itwin/core-react/issue-900_2024-07-09-07-50.json
- docs/storybook/src/components/ToolbarComposer.stories.tsx
- ui/appui-react/src/appui-react/toolbar/ToolbarItemsManager.ts
- ui/components-react/src/components-react/toolbar/useConditionalSynchedItems.ts
- ui/core-react/src/core-react/icons/ConditionalIconItem.tsx
- ui/core-react/src/core-react/icons/IconComponent.tsx
- ui/core-react/src/core-react/utils/IconHelper.tsx
- ui/core-react/src/test/icons/ConditionalIconItem.test.tsx
This PR fixes #900 by removing a `ConditionalIconItem.isConditionalIconItem()`. It was added as a workaround for #315, which I suspect might have happened due to the usage of **both** ESM and CJS modules.
Tested in standalone test-app and storybook.
> Remove `ConditionalIconItem.isConditionalIconItem()` workaround

- common/changes/@itwin/appui-react/frontstage-provider-fix_2024-07-10-09-47.json
- ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
- ui/appui-react/src/test/frontstage/FrontstageDef.test.tsx
Replace `instanceof` check of `FrontstageProvider` with the property lookup to fix `FrontstageDef.create()` if a non-instance `FrontstageProvider` is used (i.e. in `UiFramework.frontstages.addFrontstageProvider`).
Added additional unit tests.
> Fix `FrontstageDef.create()` to handle `FrontstageProvider` shaped objects

- common/changes/@itwin/appui-react/remove-theme-transition_2024-07-10-11-57.json
- common/changes/@itwin/core-react/remove-theme-transition_2024-07-10-11-57.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/theme/ThemeManager.tsx
- ui/core-react/src/core-react/colorthemes.scss
In https://github.com/iTwin/appui/issues/886, @GerardasB pointed out how iTwinUI ComboBox's menu seems to incorrectly fly in when opening the ComboBox in a popout window. Additionally, in the WidgetActionDropdown → Default story, we can see the iTwinUI flying in similarly in some cases.
Upon some collective investigation, we realized it was because the `theme-transition` CSS class on the `documentElement` was applying a `transition` to all descendants. We guess this class was meant to show a smooth transition when changing themes. However, we think changing themes is not a regular action and the current abrupt transition is good enough.
Thus, we decided to remove this `theme-transition` class altogether. This is what this PR does.
> Remove the `theme-transition` class

- docs/storybook/.gitignore
After working on #905, I noticed that storybook created some cache files that weren't gitignored. This small PR adds `.cache` to storybook's gitignore.
Old result of `git status`:
Confirmed that the `.cache` files were no longer appearing as untracked files.
> Added storybook's `.cache` to gitignore

- common/changes/@itwin/core-react/fix-popup-context-menu_2024-07-15-06-05.json
- ui/core-react/src/core-react/contextmenu/PopupContextMenu.tsx
When `PopupContextMenu` is used as a nested popup in `StatusBarPopover` it is problematic because the logic of iTwinUI (Popover) and AppUI (Popup) clash since they portal to different places which then causes various issues (e.g. the nested `Popup` displays behind the main `Popover` or opening the nested `Popup` would close the `Popover`). As a simple fix I used `portalTarget` prop which will portal the `Popup` into the `Popover` (more specifically, the trigger button which is inside the Popover).
Additionally, `PopupContextMenu` will be deprecated in AppUI 4.16.0 and can be easily replaced with `DropdownMenu` or `DropdownButton` from iTwinUI. 
Fixes #909.
Tested in standalone test-app.
> Fix `PopupContextMenu` in `StatusBarPopover`

- common/changes/@itwin/appui-react/moving-popout-widget-second-monitor-fix_2024-07-18-05-55.json
- ui/appui-react/src/appui-react/childwindow/ChildWindowConfig.ts
- ui/appui-react/src/appui-react/childwindow/InternalChildWindowManager.tsx
Moved `deltaLeft` and `deltaTop` calculations after rendering the content. Seems like when the popout widget is on the second monitor `left` and `top` values are set correctly only after the content is rendered.
Fixes #896.
Tested in electron. Regular browsers are not relevant because they will always open the child window on the primary monitor.
> Fix popout widget changing position on second monitor

- .prettierignore
- common/changes/@itwin/appui-react/fix-mixed-decl_2024-07-30-11-26.json
- common/changes/@itwin/components-react/fix-mixed-decl_2024-07-30-11-26.json
- common/changes/@itwin/core-react/fix-mixed-decl_2024-07-30-11-26.json
- common/changes/@itwin/imodel-components-react/fix-mixed-decl_2024-07-30-11-26.json
- common/config/rush/pnpm-lock.yaml
- docs/changehistory/NextVersion.md
- e2e-tests/tests/statusbar/status-bar-indicator.test.ts
- test-apps/appui-test-app/appui-test-providers/src/ui/frontstages/ComponentExamples.scss
- test-apps/appui-test-app/connected/package.json
- test-apps/appui-test-app/standalone/package.json
- test-apps/appui-test-app/standalone/src/frontend/appui/frontstages/LocalFileStage.tsx
- test-apps/appui-test-app/standalone/vite.config.mts
- ui/appui-react/src/appui-react/layout/target/_variables.scss
- ui/appui-react/src/appui-react/layout/widget/FloatingWidget.scss
- ui/appui-react/src/appui-react/layout/widget/NavigationArea.scss
- ui/appui-react/src/appui-react/layout/widget/ToolsArea.scss
- ui/appui-react/src/appui-react/layout/widget/tools/button/Button.scss
- ui/appui-react/src/appui-react/pickers/ListPicker.scss
- ui/appui-react/src/appui-react/preview/new-toolbars/ToolGroup.scss
- ui/components-react/src/components-react/editors/PopupButton.scss
- ui/components-react/src/components-react/properties/renderers/label/PropertyLabelRenderer.scss
- ui/components-react/src/components-react/propertygrid/component/PropertyGrid.scss
- ui/core-react/src/core-react/contextmenu/ContextMenu.scss
- ui/core-react/src/core-react/radialmenu/RadialMenu.scss
- ui/imodel-components-react/src/imodel-components-react/navigationaids/DrawingNavigationAid.scss
This PR fixes #911 to resolve [mixed-decls warnings](https://sass-lang.com/documentation/breaking-changes/mixed-decls/) by moving CSS declarations to the beginning of the rule.
Additionally:
- The `sass` version is bumped to the latest since `mixed-decls` is only reproducible from `1.77.7`
- CI will run `vite build` for the standalone test app to catch SASS warnings in the future
N/A
> Fix `mixed-decls` warnings

- common/api/appui-react.api.md
- common/api/core-react.api.md
- common/api/summary/appui-react.exports.csv
- common/api/summary/core-react.exports.csv
- common/changes/@itwin/appui-react/more-public-apis_2024-08-01-11-03.json
- common/changes/@itwin/core-react/more-public-apis_2024-08-01-11-03.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/framework/FrameworkDialogs.ts
- ui/appui-react/src/appui-react/statusbar/StatusBarItemUtilities.tsx
- ui/appui-react/src/appui-react/syncui/SyncUiEventDispatcher.ts
- ui/appui-react/src/appui-react/tools/FrameworkToolAdmin.ts
- ui/appui-react/src/appui-react/ui-items-provider/StandardNavigationToolsUiItemsProvider.ts
- ui/core-react/src/core-react.ts
- ui/core-react/src/core-react/listbox/Listbox.tsx
Bump more APIs to `@public` in addition to https://github.com/iTwin/appui/pull/943
N/A
> Bump more APIs to `@public`

- common/api/appui-react.api.md
- common/api/core-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/bump-accudraw_2024-08-01-13-15.json
- common/changes/@itwin/components-react/bump-accudraw_2024-08-01-13-15.json
- common/changes/@itwin/core-react/bump-accudraw_2024-08-01-13-15.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react.ts
- ui/appui-react/src/appui-react/accudraw/AccuDrawCommandItems.ts
- ui/appui-react/src/appui-react/accudraw/AccuDrawDialog.tsx
- ui/appui-react/src/appui-react/accudraw/AccuDrawFieldContainer.tsx
- ui/appui-react/src/appui-react/accudraw/AccuDrawInputField.tsx
- ui/appui-react/src/appui-react/accudraw/AccuDrawPopupManager.tsx
- ui/appui-react/src/appui-react/accudraw/AccuDrawUiSettings.ts
- ui/appui-react/src/appui-react/accudraw/AccuDrawWidget.tsx
- ui/appui-react/src/appui-react/accudraw/Calculator.tsx
- ui/appui-react/src/appui-react/accudraw/CalculatorPopup.tsx
- ui/appui-react/src/appui-react/accudraw/FrameworkAccuDraw.ts
- ui/appui-react/src/appui-react/accudraw/MenuButton.tsx
- ui/appui-react/src/appui-react/accudraw/MenuButtonPopup.tsx
- ui/appui-react/src/appui-react/accudraw/SquareButton.tsx
- ui/appui-react/src/appui-react/statusfields/toolassistance/ToolAssistanceField.tsx
- ui/components-react/src/components-react/iconpicker/IconPickerButton.tsx
- ui/core-react/src/core-react/contextmenu/ContextMenuItem.tsx
Export `AccuDrawFieldContainer` and `AccuDrawInputField` modules from the barrel file.
Promote AccuDraw APIs to `@public`.
N/A
> Export `AccuDrawFieldContainer` from a barrel file

- common/api/imodel-components-react.api.md
- common/changes/@itwin/imodel-components-react/new-timeline-prop_2024-08-05-07-08.json
- docs/changehistory/NextVersion.md
- ui/imodel-components-react/src/imodel-components-react/timeline/Scrubber.tsx
- ui/imodel-components-react/src/imodel-components-react/timeline/TimelineComponent.tsx
Added `trackContainerProps` property to `TimelineComponent`. This property is passed to iTwinUI `Slider` component.
Closes #947.
Tested in storybook.
> Added `trackContainerProps` property to `TimelineComponent`

- common/changes/@itwin/appui-react/issue-963_2024-08-14-08-42.json
- ui/appui-react/src/appui-react/hooks/useActiveViewport.tsx
- ui/appui-react/src/test/hooks/useActiveViewport.test.tsx
This PR fixes #963 by correctly syncing with the static view manager store.
Added additional unit test
> Fix `useActiveViewport` to correctly return the active viewport

- common/changes/@itwin/appui-react/fix-useConditionalValue_2024-08-14-09-18.json
- ui/appui-react/src/appui-react/hooks/useConditionalValue.tsx
- ui/appui-react/src/test/hooks/useConditionalValue.test.tsx
This PR fixes an issue where `useConditionalValue` would not handle the sync event ids correctly due to casing.
Added additional unit test.
> Fix `useConditionalValue` to handle event ids as case insensitive

- common/changes/@itwin/appui-react/fix_tool_settings_2024-08-26-13-14.json
- docs/changehistory/NextVersion.md
- test-apps/appui-test-app/appui-test-providers/src/tools/SampleTool.ts
- test-apps/appui-test-app/appui-test-providers/src/tools/ToolWithDynamicSettings.ts
- ui/appui-react/src/appui-react/uiprovider/ComponentGenerator.tsx
- ui/appui-react/src/test/frontstage/ModalSettingsStage.test.tsx
Fixed tool setting property editor not updating state after value is changed. This resulted in editor component always having only initial value and not the current value. 
Fixes https://github.com/iTwin/appui/issues/981
Did manual testing with various tools in standalone test-app. Fixed some tools to correctly update settings values as some of them were changing only in UI.
> Fixed tool setting editor not updating state after value change

- common/changes/@itwin/appui-react/fix-events-in-new-toolbars_2024-08-23-06-28.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/hooks/useConditionalProp.tsx
- ui/appui-react/src/test/hooks/useConditionalProp.test.tsx
Same problem as in #967. Noticed when debugging booster code. Studio recently enabled new toolbars so the problem now occured.
Added test for `useConditionalProp`.
> Fix new toolbars to handle event ids as case insensitive

- common/changes/@itwin/appui-react/increase-selection-count-padding_2024-08-20-12-21.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/statusfields/SelectionCount.scss
We had no padding on the right side of the `SelectionCountField` and it looked weird when there was a separator after it (the separator removes padding between different status bar fields). Changes:
- I added margins (`--iui-size-xs`) from both left and right sides now. I chose margins instead of paddings because padding is considered a part of the width so it basically decreased the `min-width` that we set (more specifically it would decrease the space reserved for more digits).
- Changed the `min-width` from `--iui-size-2xl` (equivalent to `4rem`) to `3.75rem`. This slightly decreases the min width of the component and is perfect to fit 5 digits without shifting other status bar content. I made this change because we previously had `padding-left` which is now switched to `margin-left` …
> Increase `SelectionCountField` margins

- common/changes/@itwin/appui-react/fix-menu-item-rendering_2024-08-29-06-11.json
- docs/changehistory/NextVersion.md
- test-apps/appui-test-app/appui-test-providers/src/ui/providers/ComponentExamplesProvider.tsx
- ui/appui-react/src/appui-react/shared/MenuItem.tsx
- ui/appui-react/src/test/shared/MenuItem.test.tsx
In #875 the `item` prop of `CursorMenuItemProps` was deprecated and replacement props added. However, `MenuItemHelpers.createMenuItemNode` was still checking if the `MenuItem` had `item` or `submenu`. Using the new props this condition would fail and the function would return null instead of a component node.
I changed the function to render `ContextMenuItem` by default (without any condition) so this does change the behaviour slightly. Before if the `actionItem` or `submenu` was not set it would return null but now it will return a normal node. I believe this is fine because `MenuItem` constructor already has a check that at least one of `item`, `submenu` or `execute` prop has to be used or it throws an error. So technically it should not even be possible to pass `MenuItem` without …
> Render `MenuItem` without `item` or `submenu`

- common/changes/@itwin/appui-react/fix-1002_2024-09-06-13-04.json
- docs/storybook/src/components/ToolbarComposer.stories.tsx
- ui/appui-react/src/appui-react/preview/new-toolbars/ToolGroup.scss
This PR fixes #1002 to avoid rendering a dot artifact when the toolbar is empty (with `newToolbars` preview feature enabled).
Added additional story.
> Fix `Toolbar` to avoid rendering of borders when there are no items

- common/changes/@itwin/appui-react/fix-1006_2024-09-09-10-54.json
- ui/appui-react/src/appui-react/toolbar/ToolbarItem.ts
- ui/appui-react/src/test/toolbar/Toolbar.test.tsx
This PR fixes #1006 by updating the deprecation message.
Added additional unit tests to ensure that `iconNode` is preferred over the deprecated `icon` property.
> Update deprecation message of `ToolbarActionItem["icon"]`

- common/changes/@itwin/appui-react/copy-styles-fix_2024-09-06-15-19.json
- ui/appui-react/src/appui-react/childwindow/CopyStyles.ts
This PR fixes a potential issue where a popout widget is never rendered if there's an error with one of the external resource links (stylesheets).
This was reported by one of the AppUI consumers, who managed to get around this issue by fixing the resource.
Tested manually via the `test-app`.
> Fix `copyStyles` to ignore errors on external resource links

- common/config/rush/pnpm-lock.yaml
This PR fixes `rush audit` failure due to GHSA-9wv6-86v2-598j by bumping the `express` and `express-ws` versions.
N/A
> Fix GHSA-9wv6-86v2-598j

- apps/test-app/src/frontend/appui/frontstages/MainFrontstage.tsx
- apps/test-app/src/frontend/registerFrontstages.tsx
- apps/test-providers/src/appui-test-providers.ts
- apps/test-providers/src/ui/buttons/ViewSelectorPanel.tsx
- apps/test-providers/src/ui/providers/PopoutWindowsProvider.tsx
- common/changes/@itwin/appui-react/fix-1001_2024-09-09-16-11.json
- ui/appui-react/src/appui-react/selection/SelectionContextItemDef.ts
- ui/appui-react/src/appui-react/tools/CoreToolDefinitions.tsx
- ui/appui-react/src/appui-react/utils/getActiveViewport.ts
This PR fixes #1001 by falling back to `IModelApp.viewManager.selectedView` in conditional value getters when deprecated content control APIs are not used.
Tested manually via the `test-app`.
> Fix tool conditionals that depend on active viewport when content control APIs are not used

- common/config/rush/pnpm-lock.yaml
This PR fixes `rush audit` failure due to GHSA-9wv6-86v2-598j by bumping the `express` and `express-ws` versions.
N/A
<hr>This is a backport of pull request #1012
> Fix GHSA-9wv6-86v2-598j (backport #1012)

- common/changes/@itwin/appui-react/fix-999_2024-09-10-13-57.json
- ui/appui-react/src/appui-react/statusbar/StatusBarComposer.tsx
- ui/appui-react/src/appui-react/statusbar/StatusBarCornerComponentContext.tsx
This PR fixes #999 by addressing the `undefined` property access in the out-of-bounds array within `StatusBarComposer`.
Tested manually in test-app
> Fix `undefined` property access within `StatusBarComposer` component

- common/autoinstallers/rush-lintstaged/pnpm-lock.yaml
This PR fixes `rush-lintstaged` autoinstaller causing ` ERR_PNPM_LOCKFILE_BREAKING_CHANGE ` due to incorrect `lockfileVersion`
N/A
> Fix rush-lintstaged autoinstaller

- common/api/appui-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/export-conditional-value_2024-09-16-12-56.json
- common/changes/@itwin/core-react/export-conditional-value_2024-09-16-12-56.json
- docs/changehistory/4.4.0.md
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react.ts
- ui/appui-react/src/appui-react/shared/ConditionalValue.ts
- ui/appui-react/src/appui-react/toolbar/ToolbarItemsManager.ts
- ui/appui-react/src/test/shared/ConditionalValue.test.ts
- ui/core-react/src/core-react/icons/ConditionalIconItem.tsx
This PR adds `ConditionalBooleanValue` and `ConditionalStringValue` class re-exports from `@itwin/appui-abstract` package.
`ConditionalIconValue` is removed, since it was never exported from the barrel and should have never been used via `@itwin/appui-react/lib` relative path (the class alias was added recently in the last minor).
N/A
> Correctly export conditional value classes from `@itwin/appui-abstract`

- common/api/appui-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/deprecate-internal-manager-apis_2024-09-18-15-37.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/backstage/BackstageComposer.tsx
- ui/appui-react/src/appui-react/backstage/useUiItemsProviderBackstageItems.tsx
- ui/appui-react/src/appui-react/statusbar/StatusBarComposer.tsx
- ui/appui-react/src/appui-react/statusbar/useDefaultStatusBarItems.tsx
- ui/appui-react/src/appui-react/statusbar/useUiItemsProviderStatusBarItems.tsx
This PR deprecates the `useDefaultStatusBarItems`, `useUiItemsProviderBackstageItems`, and `useUiItemsProviderStatusBarItems` hooks, which require an `@internal` class as a parameter.
N/A
> Deprecate hooks that depend on `@internal` managers

- common/changes/@itwin/appui-react/add-message-once_2024-09-23-12-30.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/messages/MessageManager.tsx
- ui/appui-react/src/test/messages/MessageManager.test.tsx
This PR changes `MessageManager.addMessage()` to ignore already active messages displayed to the user (for all message types, like `Toast` or `Sticky`). This API is used by various tools indirectly via `IModelApp.notifications.outputMessage` when `AppNotificationManager` is set up. This change should prevent the same message from being displayed multiple times unnecessarily.
Ideally, tools and other consumers should throttle the messages manually i.e. in mouse wheel scroll handlers.
In the future, an option argument can be added if there is a use case where multiple equal messages need to be added.
Additional unit tests were added and tested via the test app.
> Updated `MessageManager.addMessage` to only add unique messages

- ui/appui-react/src/appui-react/childwindow/InternalChildWindowManager.tsx
- ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
- ui/appui-react/src/appui-react/layout/state/NineZoneAction.ts
- ui/appui-react/src/appui-react/layout/state/NineZoneStateReducer.ts
- ui/appui-react/src/appui-react/layout/state/SavedTabState.ts
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
- ui/appui-react/src/test/frontstage/FrontstageDef.test.tsx
- ui/appui-react/src/test/layout/state/NineZoneStateReducer.test.ts
- ui/appui-react/src/test/layout/state/internal/TabStateHelpers.test.ts
This PR is stacked against #1062 to fix popout issues:
- Popout widgets changing size when the browser is zoomed
- `InternalChildWindowManager` will correctly clean-up event listeners
N/A
> Fix popout widget zoom issues

- apps/test-providers/src/ui/content/SampleContentControl.scss
- common/changes/@itwin/appui-react/fix-user-select_2024-10-08-12-20.json
- ui/appui-react/src/appui-react/configurableui/ConfigurableUiContent.scss
- ui/appui-react/src/appui-react/layout/widget-panels/CursorOverlay.scss
- ui/appui-react/src/appui-react/layout/widget-panels/Grip.scss
- ui/appui-react/src/appui-react/layout/widget/FloatingTab.scss
- ui/appui-react/src/appui-react/layout/widget/FloatingWidget.scss
- ui/appui-react/src/appui-react/layout/widget/MenuTab.scss
- ui/appui-react/src/appui-react/layout/widget/Overflow.scss
- ui/appui-react/src/appui-react/layout/widget/Tab.scss
- ui/appui-react/src/appui-react/layout/widget/TabBar.scss
- ui/appui-react/src/appui-react/navigationaids/SheetsModalFrontstage.scss
- ui/components-react/src/components-react/datepicker/DatePicker.scss
- ui/components-react/src/components-react/filter-builder/FilterBuilderRuleGroup.scss
- ui/core-react/src/core-react/elementseparator/ElementSeparator.scss
- ui/core-react/src/core-react/radialmenu/RadialMenu.scss
- ui/core-react/src/core-react/tree/Tree.scss
- ui/imodel-components-react/src/imodel-components-react/navigationaids/CubeNavigationAid.scss
This PR fixes #1057 by setting the [`user-select`](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) property on a stage panel resize handle to avoid content selection when resizing the panel.
Additionally, `-webkit-user-select` property is added with each `user-select` to fix widget drag/resize issues in Safari.
Tested manually in test-app.
> Fix user-select issue when resizing a stage panel

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/status-bar-popover-props_2024-10-08-17-02.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/statusbar/popup/StatusBarPopover.tsx
This PR fixes #1051 by allowing all `Popover` props to be passed into the `StatusBarPopover` and extending customization.
N/A
> Expose all `Popover` props in `StatusBarPopover` component

- common/changes/@itwin/appui-react/toolbar-opacity_2024-10-22-16-05.json
- common/changes/@itwin/components-react/toolbar-opacity_2024-10-22-16-05.json
- common/changes/@itwin/core-react/toolbar-opacity_2024-10-22-16-05.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/toolbar/new-toolbars/Surface.tsx
- ui/appui-react/src/appui-react/widgets/BackstageAppButton.tsx
- ui/appui-react/src/appui-react/widgets/NavigationWidgetComposer.tsx
- ui/appui-react/src/appui-react/widgets/ToolWidgetComposer.tsx
- ui/components-react/src/components-react/toolbar/Items.tsx
- ui/core-react/src/core-react/utils/hooks/useWidgetOpacityContext.tsx
- ui/core-react/src/test/utils/hooks/useWidgetOpacityContext.test.tsx
This PR re-adds the snap opacity behavior to the toolbars.
| Cursor is far | Cursor is close | Toolbar is hovered |
|---|---|---|
| ![Screenshot 2024-10-22 at 19 11 27](https://github.com/user-attachments/assets/835de7a2-138e-45bc-a44c-dc195e5ebb5c) | ![Screenshot 2024-10-22 at 19 11 34](https://github.com/user-attachments/assets/1c3f9246-0e88-448b-82c9-2cd6e5b6be0a) | ![Screenshot 2024-10-22 at 19 11 40](https://github.com/user-attachments/assets/05813749-c2a2-480b-9491-fccff0d37e63) |
Tested manually in the test app.
> Handle snap opacity in toolbars

- common/changes/@itwin/appui-react/add-types_2024-10-25-06-55.json
- common/changes/@itwin/components-react/add-types_2024-10-25-06-55.json
- common/changes/@itwin/core-react/add-types_2024-10-25-06-55.json
- common/changes/@itwin/imodel-components-react/add-types_2024-10-25-06-55.json
- ui/appui-react/package.json
- ui/components-react/package.json
- ui/core-react/package.json
- ui/imodel-components-react/package.json
This PR adds the `types` field back, mainly to keep the TS icon in the npm registry as recommended in https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-main-and-types
This field was removed in https://github.com/iTwin/appui/pull/1081
N/A
> Add `types` field back

- common/changes/@itwin/components-react/pw-link-fix_2024-10-30-10-55.json
- ui/components-react/src/components-react/common/Links.ts
- ui/components-react/src/components-react/properties/renderers/value/UrlPropertyValueRenderer.tsx
- ui/components-react/src/components-react/propertygrid/component/PropertyGridCommons.ts
- ui/components-react/src/test/propertygrid/component/internal/PropertyGridCommons.test.ts
Fixed `pw:` links handling in property grid. They stopped working after latest chromium updates. Suggested solution is to use custom schema links with opaque paths: `schema:<path>` instead of `schema://<path>`
https://docs.google.com/document/d/1LjxHl32fE4tCKugrK_PIso7mfXQVEeoD1wSnX2y0ZU8/edit?resourcekey=0-d1gP4X2sG7GPl9mlTeptIA&tab=t.0#heading=h.kjrmsvcywm3o
Also unified links handling between default property grid action and url property renderer.
Closes https://github.com/iTwin/appui/issues/1089
Tested manually with different browsers
> Fixed `pw:` links handling in property grid

- common/changes/@itwin/appui-react/fix-overflow_2024-10-31-14-00.json
- common/config/rush/pnpm-lock.yaml
- ui/appui-react/src/appui-react/layout/tool-settings/Docked.tsx
- ui/appui-react/src/appui-react/layout/widget/Tabs.tsx
- ui/appui-react/src/appui-react/statusbar/StatusBarComposer.tsx
This PR fixes #1080 by ignoring overflown item size changes to fix the maximum update depth error.
Additionally, the status bar will use the same overflow logic used by tool settings and widget tabs.
N/A
> Fix overflow issue in status bar overflow

- common/changes/@itwin/appui-react/css-compat_2024-11-19-16-11.json
- common/changes/@itwin/components-react/css-compat_2024-11-19-16-11.json
- common/changes/@itwin/core-react/css-compat_2024-11-19-16-11.json
- common/changes/@itwin/imodel-components-react/css-compat_2024-11-19-16-11.json
- ui/appui-react/package.json
- ui/components-react/package.json
- ui/core-react/package.json
- ui/imodel-components-react/package.json
Copy SCSS files to `cjs` and `esm` directories for backwards compatibility. 
Previously assumed https://sass-lang.com/documentation/js-api/classes/nodepackageimporter/ is not a viable solution, since it requires an explicit `pkg:` URL scheme https://sass-lang.com/documentation/at-rules/use/#pkg-ur-ls
Some bundlers/loaders do additional work to ensure that `exports` field is respected when resolving the imports (verified in `vite` and `sass-loader` for `webpack`). `esbuild-sass-plugin` does not respect the `exports` field and only built with custom `importMapper`. 
N/A
> Copy SCSS files to `cjs` and `esm` directories for compatibility

- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/todd-addfrontstage-nonbeta_2024-11-29-17-23.json
- ui/appui-react/src/appui-react/framework/FrameworkFrontstages.ts
FrameworkFrontstages.addFrontstage is the replacement of the deprecated addFrontstageProvider but it is marked as beta! In iTwin Studio we're not supposed to use any internal/alpha/beta tagged functions.
> Remove beta tag from addFrontstage since addFrontstageProvider is deprecated

- common/changes/@itwin/appui-react/remove-icons-generic_2024-12-11-15-42.json
- common/changes/@itwin/core-react/remove-icons-generic_2024-12-11-15-42.json
- common/changes/@itwin/imodel-components-react/remove-icons-generic_2024-12-11-15-42.json
- common/config/rush/pnpm-lock.yaml
- ui/appui-react/package.json
- ui/appui-react/src/appui-react/icons/snaps/SvgSnaps.tsx
- ui/appui-react/src/appui-react/icons/snaps/SvgSnapsBisector.tsx
- ui/appui-react/src/appui-react/icons/snaps/SvgSnapsCenter.tsx
- ui/appui-react/src/appui-react/icons/snaps/SvgSnapsIntersection.tsx
- ui/appui-react/src/appui-react/icons/snaps/SvgSnapsMidpoint.tsx
- ui/appui-react/src/appui-react/icons/snaps/SvgSnapsNearest.tsx
- ui/appui-react/src/appui-react/icons/snaps/SvgSnapsOrigin.tsx
- ui/appui-react/src/appui-react/layout/footer/snap-mode/Snap.scss
- ui/appui-react/src/appui-react/layout/footer/snap-mode/Snap.tsx
- ui/appui-react/src/appui-react/statusfields/SnapMode.tsx
- ui/appui-react/src/appui-react/tools/RestoreLayoutTool.tsx
- ui/appui-react/src/test/layout/footer/snap-mode/Snap.test.tsx
- ui/appui-react/src/test/statusfields/SnapMode.test.tsx
- ui/core-react/package.json
- ui/imodel-components-react/package.json
This PR resolves #798 by removing dependency on deprecated `@bentley/icons-generic` package.
N/A
> Remove `@bentley/icons-generic` from AppUI packages

- docs/storybook/.storybook/preview.ts
- docs/storybook/src/Introduction.mdx
This PR updates outdated storybook links.
Additionally, `Introduction.mdx` page will be the default storybook page instead of a first component story.
N/A
> Update outdated storybook links

- common/changes/@itwin/appui-react/issue-1170_2025-01-15-09-45.json
- e2e-tests/tests/popout-widget.test.ts
- ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
This PR fixes #1170 by correctly providing a widget id via `TabIdContext` to avoid a runtime issue in `useWidget` hook when it is used in a popout widget.
Added additional e2e test (which was failing before a fix was applied).
> Fix `useWidget` hook issue when used in a popout widget

- .prettierignore
- common/changes/@itwin/appui-react/issue-1165_2025-01-15-15-07.json
- common/changes/@itwin/components-react/issue-1165_2025-01-15-15-07.json
- common/changes/@itwin/core-react/issue-1165_2025-01-15-15-07.json
- common/changes/@itwin/imodel-components-react/issue-1165_2025-01-15-15-07.json
- ui/appui-react/src/appui-react/hooks/useTranslation.tsx
- ui/components-react/src/components-react/l10n/useTranslation.tsx
- ui/core-react/src/core-react/l10n/useTranslation.tsx
- ui/imodel-components-react/src/imodel-components-react/useTranslation.tsx
This fixes #1165 by using import attributes when importing translation string files (json files).
N/A
> Use import attributes when importing json files

- common/changes/@itwin/appui-react/mast-lodash-import-fix_2025-01-17-12-23.json
- common/changes/@itwin/components-react/mast-lodash-import-fix_2025-01-17-12-23.json
- common/changes/@itwin/core-react/mast-lodash-import-fix_2025-01-17-12-23.json
- ui/appui-react/src/appui-react/layout/base/DragManager.tsx
- ui/appui-react/src/appui-react/messages/MessageManager.tsx
- ui/appui-react/src/appui-react/pickers/ViewSelector.tsx
- ui/appui-react/src/appui-react/widget-panels/useSaveFrontstageSettings.tsx
- ui/components-react/src/components-react/tree/controlled/TreeModel.ts
- ui/core-react/src/core-react/utils/hooks/useThrottledFn.tsx
It seems with v5 there are some issues with `lodash` imports.
demo:
https://stackblitz.com/edit/stackblitz-starters-dgh2ehtd?file=package.json,index.js
> lodash import fix

- common/changes/@itwin/appui-react/fix-1185_2025-01-21-10-08.json
- common/config/rush/pnpm-lock.yaml
- ui/appui-react/package.json
This PR fixes #1185 by updating `react-error-boundary` version to avoid module loader issues in Node.js
N/A
> Update `react-error-boundary` version

- common/config/rush/pnpm-lock.yaml
This PR fixes `rush audit` failure due to `CVE-2024-52798` by bumping `express` version.
N/A
> Fix `rush audit`

- .vscode/cSpell.json
- common/autoinstallers/rush-cspell/pnpm-lock.yaml
- common/autoinstallers/rush-lintstaged/package.json
- common/autoinstallers/rush-lintstaged/pnpm-lock.yaml
- common/autoinstallers/rush-prettier/pnpm-lock.yaml
- common/config/rush/common-versions.json
- common/config/rush/pnpm-config.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
This PR updates outdated pnpm configuration by removing `ignoreCves` and `globalOverrides` entries.
Entries in `common-versions.json` are removed as well.
Auto-installers are updated via `rush update-autoinstaller --name NAME`.
N/A
> Update pnpm configuration

- apps/test-app/src/frontend/appui/frontstages/ElementStacking.tsx
Add example usage of `UiFramework.dialogs.modal.open()` that open the dialog in the popout widget.
For https://github.com/iTwin/appui/discussions/938
N/A
> `UiFramework.dialogs.modal.open()` popout example.

- apps/test-app/src/frontend/appui/frontstages/TestWidgetFrontstage.tsx
- apps/test-app/src/frontend/appui/frontstages/createTestFrontstage.tsx
- apps/test-app/src/frontend/registerFrontstages.tsx
- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/widget-useSavedState_2025-02-06-13-41.json
- docs/changehistory/NextVersion.md
- e2e-tests/tests/widget-state.test.ts
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
- ui/appui-react/src/appui-react/widgets/Widget.tsx
This PR resolves #1201 by adding `useSavedState` flag to `Widget` configuration. When enabled the widget will **NOT** be hidden after the layout is restored (i.e. page reload) when defaultState is set to Hidden (as described [in the docs](https://www.itwinjs.org/reference/appui-react/widget/widget/defaultstate/#:~:text=If%20Hidden%20the%20widget%20will%20be%20hidden%20after%20the%20layout%20is%20restored%20independently%20of%20saved%20layout%20state.)).
Added additional e2e tests
> Add `useSavedState` flag to `Widget` config

- .github/workflows/CI.yaml
- .github/workflows/extract-api.yaml
- .github/workflows/publish-storybook.yaml
- README.md
- apps/test-app/package.json
- apps/test-providers/package.json
- common/changes/@itwin/appui-react/Linas-updating-rimraf-arguments-and-deps_2025-02-14-09-12.json
- common/changes/@itwin/components-react/Linas-updating-rimraf-arguments-and-deps_2025-02-14-09-12.json
- common/changes/@itwin/core-react/Linas-updating-rimraf-arguments-and-deps_2025-02-14-09-12.json
- common/changes/@itwin/imodel-components-react/Linas-updating-rimraf-arguments-and-deps_2025-02-14-09-12.json
- common/config/azure-pipelines/jobs/docs-ci.yaml
- docs/changehistory/NextVersion.md
- rush.json
- ui/appui-react/package.json
- ui/components-react/package.json
- ui/core-react/package.json
- ui/imodel-components-react/package.json
Rimraf package have been previously upgraded from version `3` to version `6` in our `package.json` files. However, since version `4` it requires `--glob` option in order to accept paths that contain star symbol (`*`). Without `--glob` option `npm run clean` failed on my Windows machine. Also, now package requires Node version 20 or higher.
https://www.npmjs.com/package/rimraf
- Added `-g` option to `rimraf` command in package.json files.
- Updated required Node version to `20.0.0` and updated readme file.
- Updated node version in pipelines
After adding `-g` option `npm run clean` no longer fails.
> Adding -g option to rimraf and updating node version

- docs/storybook/src/frontstage/ToolSettings.stories.tsx
- docs/storybook/src/frontstage/ToolSettings.tsx
- docs/storybook/src/tools/CustomEditorTool.tsx
Closes #1204 by adding a tool settings story that uses a custom editor component.
New story renders [iTwinUI Tag](https://itwinui.bentley.com/docs/tag) components in tool setting area by using tool setting APIs.
Live demo: https://itwin.github.io/appui/1226/?path=/story/frontstage-toolsettings--custom-editor
N/A
> Add tool setting with custom editor story

- .github/workflows/CI.yaml
- .github/workflows/extract-api.yaml
- .github/workflows/publish-storybook.yaml
- common/config/azure-pipelines/jobs/docs-ci.yaml
- common/config/azure-pipelines/jobs/version-bump-individual.yaml
- common/config/azure-pipelines/jobs/version-bump.yaml
Update leftover Node.js v18 usage of https://github.com/iTwin/appui/pull/1214 which caused issues in release pipeline.
N/A
> Update Node.js version used in release pipelines

- common/config/azure-pipelines/jobs/docs-ci.yaml
Both agent pools in docs-ci should migrate off iModelTechCi.
> docs ci: one more agent pool to update

- common/config/rush/pnpm-lock.yaml
This PR fixes `rush audit` failure due to [CVE-2024-52798](https://github.com/advisories/GHSA-jr5f-v2jv-69x6) by bumping the `axios` version.
N/A
> Update `axios` version

- apps/test-app/src/frontend/appui/frontstages/SpatialFrontstage.tsx
- common/api/appui-react.api.md
- common/changes/@itwin/appui-react/layouts-ui-items-manager_2025-03-14-14-42.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/UiFramework.ts
- ui/appui-react/src/appui-react/toolbar/ToolbarItem.ts
- ui/appui-react/src/appui-react/ui-items-provider/AbstractUiItemsManager.ts
- ui/appui-react/src/appui-react/ui-items-provider/UiItemsManager.ts
- ui/appui-react/src/appui-react/widgets/Widget.tsx
- ui/appui-react/src/test/ui-items-provider/UiItemsManager.test.tsx
This PR adds `UiItemsManager.getToolbarItems` method and `UiItemsManager.getWidgets` method overload to return registered items that are not configured for the standard layout. This is useful when implementing custom layouts, since standard layout specific definitions, like `ToolbarUsage` can be omitted.
Usage examples are available in `NextVersion.md`
Added additional unit tests.
> Update `UiItemsManager` to return items for custom layouts

- apps/test-app/README.md
- common/changes/@itwin/appui-react/fix-1239_2025-03-19-15-50.json
- ui/appui-react/src/appui-react/childwindow/InternalChildWindowManager.tsx
This PR fixes #1239 which is reproducible in Firefox only. The main cause for the issue was style loading failure in https://github.com/iTwin/appui/blob/28181ab49f89b4e8d3162c7324b648e32077637b/ui/appui-react/src/appui-react/childwindow/CopyStyles.ts#L11
Reason for failure:
- https://developer.mozilla.org/en-US/docs/Web/API/Window/open is used to open a new blank page (empty string is used for url param)
- `window.location.href` of new window equals to `about:blank`
- `window.document.baseURI` of new window equals to the `baseURI` of the `opener` (main window), i.e. `http://localhost:3000/blank?frontstageId=widget-api&useDefaultPopoutUrl=0` when ran locally.
- **[Firefox only]** `window.document.baseURI` of new window equals to `about:blank`
- …
> Fix Firefox specific style loading issue in widget popouts

- common/changes/@itwin/appui-react/standard-layout-rsbuild_2025-03-30-16-39.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/layout/StandardLayout.scss
This PR fixes #1259 by simplifying the grid template definitions of standard layout to avoid CSS issues in `rsbuild` production build.
Tested manually by running `rsbuild` w/ matching CSS rules.
> Fix standard layout for `rsbuild`

- common/changes/@itwin/appui-react/on-item-executed_2025-03-31-08-16.json
- docs/changehistory/NextVersion.md
- docs/storybook/src/components/ToolbarPopup.stories.tsx
- docs/storybook/src/components/ToolbarPopup.tsx
- ui/appui-react/src/appui-react/toolbar/Toolbar.tsx
- ui/appui-react/src/appui-react/toolbar/new-toolbars/ActionItem.tsx
- ui/appui-react/src/appui-react/toolbar/new-toolbars/GroupItem.tsx
- ui/appui-react/src/appui-react/toolbar/new-toolbars/Toolbar.tsx
This PR fixes #1234 by correctly invoking `onItemExecuted` prop of the `Toolbar` component which was omitted from the initial implementation of the updated toolbar
Added additional story.
> Fix `onItemExecuted` of the `<Toolbar>` component

- apps/test-providers/src/tools/SampleTool.tsx
- common/api/appui-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/cursor-menu-fix_2025-03-31-09-19.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/cursor/cursormenu/CursorMenu.tsx
- ui/appui-react/src/appui-react/shared/MenuItem.tsx
This PR fixes #1235 by correctly rendering an icon specified via `iconNode` property of `CursorMenuItemProps` interface in `CursorPopupMenu` component.
Additionally, `iconRight` property of `CursorMenuItemProps` is deprecated and replaced by newly introduced `iconRightNode`.
`CursorPopupMenu` component is converted from a class component to a functional one.
Tested manually via test-app (alt+click when "SampleTool" is active).
> Fix `iconNode` rendering of `CursorMenuItemProps`

- common/changes/@itwin/appui-react/tool-settings-widget_2025-03-30-20-45.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/configurableui/ConfigurableUiContent.tsx
This PR fixes #1227 by adding `visibleToolSettings` prop to `StandardLayout` component which when enabled keeps the tool settings visible to the end user. This is especially useful when the tool settings is undocked as a regular widget as changing a tool or it's tool settings will show the tool settings widget via the `WidgetDef.show()` API.
Tested manually via test-app.
> Add `visibleToolSettings` prop to `<StandardLayout>`

- apps/test-app/src/frontend/App.tsx
- apps/test-providers/src/ui/providers/ContentLayoutStageUiItemsProvider.tsx
- common/api/appui-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/prompt-at-cursor_2025-04-11-11-26.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/childwindow/ChildWindowRenderer.tsx
- ui/appui-react/src/appui-react/configurableui/ConfigurableUiContent.tsx
- ui/appui-react/src/appui-react/content/ContentLayout.tsx
- ui/appui-react/src/appui-react/content/ContentOverlay.tsx
- ui/appui-react/src/appui-react/content/FloatingViewportContent.tsx
- ui/appui-react/src/appui-react/cursor/CursorInformation.ts
- ui/appui-react/src/appui-react/cursor/cursorpopup/CursorPopupManager.tsx
- ui/appui-react/src/appui-react/cursor/cursorprompt/CursorPrompt.tsx
- ui/appui-react/src/appui-react/framework/FrameworkVisibility.ts
- ui/appui-react/src/appui-react/ui-items-provider/StandardStatusbarUiItemsProvider.tsx
- ui/appui-react/src/appui-react/utils/InternalUiShowHideManager.ts
- ui/appui-react/src/test/configurableui/ConfigurableUiContent.test.tsx
- ui/appui-react/src/test/frontstage/FrontstageManager.test.tsx
- ui/appui-react/src/test/utils/UiShowHideManager.test.tsx
This PR closes #1242 by adding capability to display prompt at cursor in child windows and popout widgets. Tool assistance prompt at cursor is one such use case, available with `ToolAssistanceField`. Additional information and usage guidance is available in `NextVersion.md`.
Additionally, `CursorPopupRenderer` class component is converted to a functional component.
Future work involves refactoring of `ToolAssistanceField` and will be done in subsequent PRs. Known issues:
- Cursor prompt is displayed when dragging a widget container or a widget tab
- Cursor prompt is rendered below floating widgets
- Cursor prompt timing issues, where timeout is not respected if prompt is re-shown when fading out
N/A
> Add ability to render prompt at cursor in child windows

- common/api/appui-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/tool-assistance-prompt_2025-04-15-15-41.json
- docs/changehistory/NextVersion.md
- e2e-tests/tests/notification/tool-assistance-field.test.ts
- ui/appui-react/src/appui-react/configurableui/ConfigurableUiContent.tsx
- ui/appui-react/src/appui-react/cursor/cursorpopup/CursorPopup.scss
- ui/appui-react/src/appui-react/cursor/cursorprompt/CursorPrompt.tsx
- ui/appui-react/src/appui-react/hooks/useActiveTool.tsx
- ui/appui-react/src/appui-react/layout/base/DragManager.tsx
- ui/appui-react/src/appui-react/statusfields/toolassistance/ToolAssistanceField.tsx
- ui/appui-react/src/test/statusfields/toolassistance/ToolAssistanceField.test.tsx
Follow up to _#1277_
This PR fixes following issues with tool assistance cursor prompt:
- Displayed when dragging a widget container or a widget tab (when `promptAtContent` is enabled)
- Rendered below floating widgets
- Timing issues, where timeout is not respected if prompt is re-shown when fading out
Additionally, `ToolAssistanceField` is refactored from class to functional component.
Internal changes:
- Added `useActiveTool` (currently marked as internal), although this could be exposed as well.
- `useDraggedItem` is now using `useSyncExternalStore` to avoid weird timing/rendering issues between React state and `zustand` store.
N/A
> Fix issues with tool assistance prompt

- apps/test-app/src/frontend/appui/frontstages/TestToolSettingsFrontstage.tsx
- apps/test-app/src/frontend/registerFrontstages.tsx
- common/changes/@itwin/appui-react/master_2025-04-16-15-54.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/configurableui/ConfigurableUiContent.tsx
- ui/appui-react/src/appui-react/layout/state/NineZoneAction.ts
- ui/appui-react/src/appui-react/layout/state/NineZoneStateReducer.ts
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
This PR closes #1268 by introducing `toolSettings.defaultLocation` prop to `StandardLayout` component.
Added additional frontstage to the `test-app` to test tool settings specific wokrflows `?frontstageId=test-tool-settings&location=right&section=0`.
> Tool settings location

- apps/test-app/src/frontend/SearchParams.tsx
- common/api/appui-react.api.md
- common/api/summary/appui-react.exports.csv
- common/changes/@itwin/appui-react/initialize-frontstages_2025-04-16-20-57.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react.ts
- ui/appui-react/src/appui-react/UiFramework.ts
- ui/appui-react/src/appui-react/framework/FrameworkFrontstages.ts
- ui/appui-react/src/appui-react/frontstage/InternalFrontstageManager.ts
- ui/appui-react/vitest.config.ts
This PR closes #1255 by allowing consumers to override `UiFramework.frontstages` via `UiFramework.initialize`. See `NextVersion.md` for an example.
Newly added `DefaultFrameworkFrontstages` is marked as alpha, until tested in the consuming application.
Tested manually in the `test-app`.
> Add ability to override `UiFramework.frontstages`

- common/api/components-react.api.md
- common/changes/@itwin/components-react/editor-show-status-message_2025-04-24-10-13.json
- common/changes/@itwin/components-react/editor-show-status-message_2025-04-24-10-18.json
- docs/changehistory/NextVersion.md
- docs/storybook/src/components/FilterBuilder.stories.tsx
- docs/storybook/src/components/FilterBuilder.tsx
- ui/components-react/src/components-react/filter-builder/FilterBuilderRule.tsx
- ui/components-react/src/components-react/filter-builder/FilterBuilderRuleValue.tsx
- ui/components-react/src/components-react/new-editors/EditorRenderer.tsx
- ui/components-react/src/components-react/new-editors/editors/NumericEditor.tsx
- ui/components-react/src/test/new-editors/EditorRenderer.test.tsx
Closes https://github.com/iTwin/appui/issues/1219. Added ability to show status message along size editor. 
Didn't change `FilterBuilder` to use this new approach when using new editors system to have better backwards compatibility. 
Added unit tests.
> Editor show status message

- apps/test-providers/src/ui/providers/PreviewFeaturesToggleProvider.tsx
- common/changes/@itwin/appui-react/new-editors-in-tool-settings_2025-04-24-13-36.json
- docs/changehistory/NextVersion.md
- ui/appui-react/src/appui-react/preview/PreviewFeatures.tsx
- ui/appui-react/src/appui-react/preview/tool-settings-new-editors/useToolsSettingsNewEditors.ts
- ui/appui-react/src/appui-react/uiprovider/ComponentGenerator.tsx
Closes https://github.com/iTwin/appui/issues/1223. Added preview feature for enabling usage of the new editors system in tool settings.
Tool settings with legacy editors system:
Tool settings with new editors system:
> [preview-feature]: New editors system in tool settings

- .github/workflows/changeset-release.yaml
This should fix a release failure due to missing `id-token` permissions:
`an error occurred while publishing @itwin/imodel-components-react: EUSAGE Provenance generation in GitHub Actions requires "write" access to the "id-token" permission`
N/A
> Retry release

- .github/workflows/changeset-release.yaml
This should fix future releases due to permissions failure which caused GH release creation and commit tagging failures when releasing 5.5.0.
N/A
> Fix future releases

- ui/appui-react/package.json
This was missed by https://github.com/iTwin/appui/pull/1295
N/A
> Lock `@itwin/core-react` version in `@itwin/appui-react`

- .changeset/curly-pumas-cover.md
- ui/components-react/src/components-react/propertygrid/dataproviders/FilteringDataProvider.ts
- ui/components-react/src/components-react/tree/controlled/TreeEventHandler.ts
This fixes a potential infinite recursion caused by superclasses that need to call `super.dispose` in their `[Symbol.dispose]` method (i.e. when needing to support older versions - before `Symbol.dispose` was introduced).
N/A
> Fix potential infinite recursion in `dispose`

- .changeset/fluffy-gifts-judge.md
- .changeset/major-steaks-admire.md
- common/api/components-react.api.md
- docs/storybook/src/preview/ToolSettingsLockButton.stories.tsx
- docs/storybook/src/preview/ToolSettingsLockButton.tsx
- ui/appui-react/src/appui-react/editors/LockProvider.tsx
- ui/appui-react/src/appui-react/new-editors/CustomNumberEditor.tsx
- ui/appui-react/src/appui-react/new-editors/LockEditor.tsx
- ui/appui-react/src/appui-react/new-editors/NumericEditor.tsx
- ui/appui-react/src/appui-react/new-editors/TextEditor.tsx
- ui/appui-react/src/appui-react/preview/tool-settings-lock-button/useToolSettingsLockButton.tsx
- ui/appui-react/src/appui-react/widget-panels/ToolSettings.tsx
- ui/components-react/src/components-react/new-editors/editors-registry/EditorsRegistryProvider.tsx
- ui/components-react/src/components-react/new-editors/interop/old-editors/CustomNumber.tsx
- ui/components-react/src/internal.ts
This PR continues on https://github.com/iTwin/appui/pull/1311 to add lock button decoration capability when new editor system is enabled.
N/A
> Lock button in new editors

- .changeset/moody-turkeys-spend.md
- docs/storybook/src/components/ToolAssistanceField.stories.tsx
- ui/appui-react/src/appui-react/hooks/useControlledState.ts
- ui/appui-react/src/appui-react/statusfields/toolassistance/ToolAssistanceField.tsx
This PR closes #1307 by adding `visible`, `pinned` and related `onVisibleChange`, `onPinnedChange` props to the `ToolAssistanceField` component. This change enables consumers to manually control whether the field is visible and pinned.
Added additional story.
https://itwin.github.io/appui/1325/?path=/story/components-status-fields-toolassistancefield--controlled
> Add controlled props to `ToolAssistanceField` component

- .changeset/strong-swans-burn.md
- apps/test-providers/src/ui/providers/PreviewFeaturesToggleProvider.tsx
- docs/storybook/src/preview/ToolSettingsKeyPressCommit.stories.tsx
- docs/storybook/src/preview/ToolSettingsKeyPressCommit.tsx
- docs/storybook/src/tools/CustomEditorTool.tsx
- docs/storybook/src/tools/LockPropertyTool.ts
- docs/storybook/src/tools/StoryTool.ts
- ui/appui-react/src/appui-react/editors/CustomNumberEditor.tsx
- ui/appui-react/src/appui-react/editors/NumericEditor.tsx
- ui/appui-react/src/appui-react/editors/TextEditor.tsx
- ui/appui-react/src/appui-react/preview/PreviewFeatures.tsx
- ui/appui-react/src/appui-react/preview/tool-settings-key-press-commit/useToolSettingsKeyPressCommit.tsx
- ui/appui-react/src/appui-react/widget-panels/ToolSettings.tsx
- ui/appui-react/vitest.config.ts
- ui/components-react/src/components-react/editors/CustomNumberEditor.tsx
This PR adds `toolSettingsKeyPressCommit` preview feature, which when enabled the input-like editors rendered in the tool settings will commit the entered value on each key press. This behavior is available only with legacy editor system, when `toolSettingsNewEditors` is not enabled.
Added additional stories.
https://itwin.github.io/appui/1329/?path=/story/previewfeatures-toolsettingskeypresscommit--default
> Add `toolSettingsKeyPressCommit` preview feature

- .github/workflows/CI.yaml
- apps/test-app/package.json
- apps/test-providers/package.json
- docs/storybook/package.json
- e2e-tests/package.json
- tools/codemod/package.json
This PR adds [sharding](https://vitest.dev/guide/improving-performance.html#sharding) to unit tests when running on CI to improve the speed.
This should save around 4 minutes of wait time from current ~11 minutes.
Additionally removed unused empty script definitions (previously required by `rush.js`).
N/A
> Add sharding to unit tests on CI

- .changeset/nasty-doors-fry.md
- apps/test-app/src/frontend/appui/frontstages/TestToolSettingsFrontstage.tsx
- apps/test-app/src/frontend/appui/frontstages/TestWidgetFrontstage.tsx
- apps/test-app/src/frontend/appui/frontstages/createTestFrontstage.tsx
- e2e-tests/tests/Utils.ts
- e2e-tests/tests/tool-settings.test.ts
- ui/appui-react/src/appui-react/hooks/useLatestRef.tsx
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
This PR fixes #1323 by correctly initializing the tool settings location when frontstage layout is restored.
Added additional e2e test.
> Fix tool settings location when layout is restored

- .changeset/chubby-crabs-attack.md
- ui/appui-react/src/appui-react/hooks/useActiveIModelConnection.tsx
- ui/appui-react/src/test/TestUtils.ts
- ui/appui-react/src/test/hooks/useActiveIModelConnection.test.tsx
This PR closes #1215 by refactoring `useActiveIModelConnection` hook. This removes the requirement for having a redux store configured, when using the hook.
Refactored existing and added additional unit test.
> Refactor `useActiveIModelConnection` hook

- .changeset/slimy-bobcats-feel.md
- apps/test-app/src/frontend/appui/frontstages/TestToolSettingsFrontstage.tsx
- apps/test-app/src/frontend/appui/frontstages/TestWidgetFrontstage.tsx
- docs/storybook/src/Utils.tsx
- docs/storybook/src/frontstage/ToolSettings.stories.tsx
- docs/storybook/src/frontstage/ToolSettings.tsx
- e2e-tests/tests/tool-settings.test.ts
- ui/appui-react/src/appui-react/configurableui/ConfigurableUiContent.tsx
- ui/appui-react/src/appui-react/layout/state/NineZoneAction.ts
- ui/appui-react/src/appui-react/layout/state/NineZoneStateReducer.ts
- ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
- ui/appui-react/src/appui-react/widgets/Widget.tsx
- ui/appui-react/src/test/layout/state/NineZoneStateReducer.test.ts
This PR closes #1320 by enhancing the tool settings layout initialization. When `toolSettings.defaultLocation` is set on `StandardLayout` component the tool settings will be initialized as a regular widget.
Added additional e2e test.
To test in `test-app`: `/blank?frontstageId=test-tool-settings&location=right&defaultState=floating`
Added additional stories:
https://itwin.github.io/appui/1353/?path=/story/frontstage-toolsettings--widget
https://itwin.github.io/appui/1353/?path=/story/frontstage-toolsettings--floating
> Configure tool settings as a regular widget

- .changeset/sweet-spies-camp.md
- ui/appui-react/src/appui-react/widgets/NavigationWidgetComposer.tsx
This PR fixes #1332 by correctly updating the navigation aid when view class name is changed while content control is active in the `NavigationAidHost` component.
Previously the event handler of `onViewClassFullNameChangedEvent` was doing nothing, since the `activeViewClass` variable  was not used.
Tested in `test-app`, i.e.  `/local/Baytown.bim?frontstageId=custom-content`
And temporary adding a view selector to that frontstage: `getCustomViewSelectorPopupItem()` to `CustomContentStageUiProvider`.
> Fix navigation aid of `NavigationAidHost`

- .changeset/mighty-needles-stop.md
- .changeset/red-pugs-remain.md
- apps/test-app/src/frontend/appui/frontstages/WidgetApiFrontstage.tsx
- common/api/appui-react.api.md
- docs/storybook/src/components/ToolbarComposer.stories.tsx
- ui/appui-react/src/appui-react/toolbar/ToolbarComposer.tsx
- ui/appui-react/src/appui-react/toolbar/ToolbarItem.ts
- ui/appui-react/src/appui-react/toolbar/ToolbarItemsManager.ts
- ui/appui-react/src/appui-react/toolbar/new-toolbars/GroupItem.tsx
- ui/appui-react/src/appui-react/toolbar/new-toolbars/Item.tsx
This PR fixes #1381 by adding an `isActiveCondition` property to `CommonToolbarItem` interface as a replacement to now deprecated `isActive` property.
This change adds similar capability to https://github.com/iTwin/appui/pull/1379, however the active state management is done from the toolbar item itself (usually in a `UiItemsProvider`), which is handy for package developers and avoids explicit/global active toolbar item management.
Applications, that want explicit control over what toolbar items are active should use the `Toolbar` component directly and override the `isActive/isActiveCondition` properties.
- Updated storybook story to use the conditional value for active state: https://itwin.github.io/appui/1383/?path=/story/components-toolbarcomposer--conditional
- Updated …
> Add `isActiveCondition` property to `CommonToolbarItem` interface

- .changeset/wild-corners-flow.md
- ui/components-react/src/components-react/new-editors/interop/EditorInterop.ts
- ui/components-react/src/test/new-editors/interop/EditorInterop.test.ts
Fixed `EditorInterop` not propagating `quantityType` from `PropertyRecord` to `ValueMetada`
Added unit test
> [components-react] EditorInterop drops quantityType from PropertyRecord

- apps/test-app/package.json
- docs/storybook/package.json
- package.json
- pnpm-lock.yaml
This PR fixes `pnpm audit` failures by bumping dependency versions of `vite-plugin-static-copy` and `@changesets/cli`.
N/A
> Fix `pnpm audit` failures

- .changeset/pretty-bugs-study.md
- ui/appui-react/src/appui-react/layout/widget-panels/Grip.scss
This PR updates colors used in `WidgetPanelGrip` component to correctly match the iTwinUI CSS variables semantically.
| Descr | Before | After |
| --- | --- | --- |
| iTwinUI | <img width="92" height="211" alt="Screenshot 2025-08-29 at 15 59 23" src="https://github.com/user-attachments/assets/c2dabcf1-e39f-431c-80c0-f5fe329ebf79" /> | <img width="79" height="202" alt="Screenshot 2025-09-03 at 10 36 31" src="https://github.com/user-attachments/assets/54af2de8-a7bc-46ce-a198-ba4ce4cdb11a" /> |
| iTwinUI + `themeBridge` | <img width="105" height="235" alt="Screenshot 2025-08-29 at 15 59 01" src="https://github.com/user-attachments/assets/5c7b4a6f-ac5c-4015-b851-40402a6f7311" /> | <img width="58" height="220" alt="Screenshot 2025-09-03 at 10 35 03" …
> Update colors of `<WidgetPanelGrip />`

- .changeset/social-paths-push.md
- ui/appui-react/src/appui-react/layout/footer/dialog/Dialog.scss
- ui/appui-react/src/appui-react/layout/footer/snap-mode/Panel.scss
- ui/appui-react/src/appui-react/statusfields/message-center/MessageCenterField.scss
When the message centre is used in combination with the tool assistant and snap mode elements in the status bar, and the stratakit bridge is used, we can see a discrepancy between the backgrounds of the message centre and other popover panels. The issue is that stratakit [sets a background colour](https://github.com/iTwin/iTwinUI/blob/9d6a12a7f8eabc11898edb1e1471af38d571fe9c/packages/itwinui-css/src/bridge.scss#L322) on `.iui-popover-surface`. The [toolbox assistant](https://github.com/iTwin/appui/blob/2b75e0523a022ce72f1f53abec2805e9606fa64e/ui/appui-react/src/appui-react/statusfields/toolassistance/ToolAssistanceField.scss#L33) and [snap mode](https://github.com/iTwin/appui/blob/2b75e0523a022ce72f1f53abec2805e9606fa64e/ui/appui-react/src/appui-react/layout/footer/snap-mode/Panel.scss#L8) …
> Set default message centre popover background

- .changeset/empty-bears-cough.md
- docs/storybook/src/components/ToolbarComposer.stories.tsx
- ui/appui-react/src/appui-react/toolbar/new-toolbars/GroupItem.scss
- ui/appui-react/src/appui-react/toolbar/new-toolbars/GroupItem.tsx
- ui/appui-react/src/appui-react/toolbar/new-toolbars/OverflowButton.tsx
This PR fixes #1366 by removing the height limit that caused vertical overflow in dropdown menus of `Toolbar` component.
| Before | After |
| --- | --- |
|  <img width="653" height="625" alt="Screenshot 2025-09-25 at 16 00 39" src="https://github.com/user-attachments/assets/64dbe7e2-d716-4349-a561-97876f90a877" /> | <img width="649" height="944" alt="Screenshot 2025-09-25 at 16 01 08" src="https://github.com/user-attachments/assets/693075b2-aa25-447d-b046-3d87fa248909" /> |
Additionally, fixed a dev-only warning: https://github.com/iTwin/iTwinUI/blob/f0faefbbe4e8bd7867a29ab89212317e903768a6/packages/itwinui-react/src/core/Menu/MenuItem.tsx#L127
Added additional story: https://itwin.github.io/appui/1419/?path=/story/components-toolbarcomposer--overflow
> Remove overflow from `Toolbar` component

- .changeset/odd-peas-rescue.md
- common/api/appui-react.api.md
- docs/storybook/src/frontstage/Modal.stories.tsx
- docs/storybook/src/frontstage/Modal.tsx
- ui/appui-react/src/appui-react/framework/FrameworkFrontstages.ts
This PR closes #1395 by adding an `id` property to `ModalFrontstageInfo` interface. `id` property is optional for backwards compatibility.
This change allows consumers to uniquely identify modal frontstages, when `id` is specified when opening a modal frontstage via `UiFramework.frontstages.openModalFrontstage()`.
Updated stories of `ModalFrontstage` https://itwin.github.io/appui/1431/?path=/story/frontstage-modalfrontstage--basic
> Add `id` property to `ModalFrontstageInfo`

- .changeset/two-tigers-lie.md
- apps/test-app/src/frontend/appui/frontstages/EditorFrontstage.tsx
- ui/appui-react/src/appui-react/accudraw/AccuDrawKeyboardShortcuts.ts
Fixes first part for #1189 by removing the `isHidden` conditional values from lock shortcuts.
| Before | After |
| --- | --- |
|  <img width="277" height="405" alt="Screenshot 2025-10-08 at 15 58 26" src="https://github.com/user-attachments/assets/754a8b1a-bd58-4d6e-a3f3-0c0794aff058" /> | <img width="278" height="548" alt="Screenshot 2025-10-08 at 15 57 52" src="https://github.com/user-attachments/assets/90ad05ae-2d76-4a2a-8c0a-d9407b7ffbf6" /> |
Verified, that compass mode is changed when locking an unrelated field, i.e.: `Lock X` while in polar mode changes the compass to rectangular mode.
Tested in `Editor` frontstage of `test-app` after opening a local iModel: `/local/Baytown.bim?frontstageId=editor`
> Remove `isHidden` conditionals from lock field shortcuts of AccuDraw
